### ISSUE TITLE
[Table] Empty rows shown

### ISSUE THREAD

**Issue by EricWilson-HV** [lumada-design/hv-uikit-react#2400]
**Describe the bug**
If the number of rows to show exceeds the number of entries it is showing empty rows instead of truncating them

**To Reproduce**
1. Go to the Table in the Story Book
2. Click on Click on Show Rows drop down and set to 20
3. There are only 13 items in the table but we are displaying all 20 rows. 

**Expected behavior**
We should only be showing 13 items in the table since that is all that there are, and should not show the empty rows.

**Enviroment (please complete the following information):**
Storybook

**Comment by diogofscmariano** [comment]
@EricWilson-HV we now have a new table in lab which in the long term is the one replacing this component. This is no longer reproducible there, plus, we added a lot of new capabilities. Closing this one for now, if it is still relevant let us know
