### ISSUE TITLE
HvBaseDropdown renders elements with widths that don't match

### ISSUE THREAD

**Issue by afrjorge** [lumada-design/hv-uikit-react#2479]
**Describe the bug**
When the `HvBaseDropdown` component is rendered with a width that has decimals, the `div` with class `HvBaseDropdown-inputExtensionOpen` has its width rounded and doesn't match the dropdown width.

**To Reproduce**
1. Render a `HvBaseDropdown` with a width with decimals
2. Click to open the dropdown
3. See that the `div` `HvBaseDropdown-root` and the `div` `HvBaseDropdown-inputExtensionOpen` have different widths

**Expected behaviour**
`HvBaseDropdown-root` and `HvBaseDropdown-inputExtensionOpen` should have the same width.

**Screenshots**
<img width="787" alt="HvBaseDropdown_widths_mismatch" src="https://user-images.githubusercontent.com/6838546/123977216-b6423680-d9b6-11eb-8a38-1f477ff44f72.png">

**Enviroment (please complete the following information):**
 - Device: Laptop
 - OS: macOS Catalina 10.15.7
 - Browser: chrome 91
 - Version 3.30

**Comment by francisco-guilherme** [comment]
This issue was closed because it has been inactive.
