### ISSUE TITLE
HvTextArea performance degrades over time if autoScroll is enabled

### ISSUE THREAD

**Issue by afrjorge** [lumada-design/hv-uikit-react#2564]
**Describe the bug**
It seems that the initial feature request was to have the autoScroll feature stop if the user scrolls up, and resume when the scroll is back at the bottom. Currently if the user scrolls up the component will automatically scroll to the bottom and add more scroll event listeners. After a while of trying to scroll up the component ends up adding an excessive amount of scroll event listeners and the component performance degrades.

**To Reproduce**
1. Render an HvTextArea with autoScroll enabled
2. Scroll up a few times
3. See that the component automatically scrolls down and has added several scroll event listeners

**Expected behavior**
If the user scrolls up the autoScroll should be disabled, until the user scrolls back to the bottom. Only one scroll event listeners should exist and the component should remove it when it is unmounted.

**Enviroment (please complete the following information):**
 - Device: Laptop, Mobile
 - OS: macOS Catalina 10.15.7
 - Browser chrome
 - Version 93

**Additional context**
Dataflow Manager currently does not use this feature anymore, so an alternative might be to remove it and have the user  implement it if required.

**Comment by plagoa** [comment]
A fix for this has been released on version `3.56.1` of the `uikit-react-core` package. Closing this issue, let us know if there's still any issue.
