### ISSUE TITLE
[TypeScript] HvCardMediaProps don't include certain props, i.e component="img"

### ISSUE THREAD

**Issue by Piyush-hitachi** [lumada-design/hv-uikit-react#2591]
**Describe the bug**
While using the HvCardMedia of HvCard component for our project purpose I recognized that ts throws a compile error on the HvCardMedia component.

>Type ‘{ image: string; component: string; alt: string; height: number; }’ is not assignable to type ‘IntrinsicAttributes & Pick<CardMediaProps<“div”, {}>, “title” | “color” | “translate” | “hidden” | “style” | “ref” | “slot” | “image” | ... 250 more ... | “src”> & StyledComponentProps<...> & { ...; }’.
  Property ‘component’ does not exist on type ‘IntrinsicAttributes & Pick<CardMediaProps<“div”, {}>, “title” | “color” | “translate” | “hidden” | “style” | “ref” | “slot” | “image” | ... 250 more ... | “src”> & StyledComponentProps<...> & { ...; }’.

**To Reproduce**
1. Use component attributes of HvCardMedia in your project 
2.  The ts compiler will throw the error on HvCardMedia

**Expected behavior**
TypeScript should not throw an error if you use properties which get passed to the used component.

**Enviroment (please complete the following information):**
 - Device: Laptop
 - OS: macOS Big Sur version 11.6.1
 - Browser : chrome
 - Version : 95.0.4638.54

**Comment by francisco-guilherme** [comment]
Hi @Piyush-hitachi, 

this was fixed by #2724, and is available on [3.62.1](https://github.com/lumada-design/hv-uikit-react/compare/@hitachivantara/uikit-react-core@3.62.0...@hitachivantara/uikit-react-core@3.62.1).

Tks for reaching out.
