### ISSUE TITLE
Addind a OnSelect 

### ISSUE THREAD

**Issue by FranciscoPereiraXpand** [lumada-design/hv-uikit-react#2663]
Ui-Kit version 2.22.0

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

There is no current functionality like this one so it's a new one.

### Expected behavior 🤔

I need an OnSelect so when the user selects a box in the dropdown Menu I can display a popUp when  the user selects more than 4 boxes. 

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

Need this onSelect for a Critical error that im fixing. 

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by diogofscmariano** [comment]
We ended up working around this using a different strategy. If this is still relevant please let us know
