### ISSUE TITLE
For Bar chart, Upper scale is not present for Y-axis.

### ISSUE THREAD

**Issue by rajashriDalavi** [lumada-design/hv-uikit-react#2666]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

 For Bar chart, Upper scale is not present for Y-axis. if total transaction are 1300+ then It should plot up-to 1400 on Y axis. But it showing only up-to 1200.

### Expected behavior 🤔

If upper scale or graph point for Y-axis is 1380. Then Y-axis should be plot up-to 1400 or 1380.
But currently it's not showing upper scale.

### Steps to reproduce 🕹

Steps:

1. Go to URL - https://lumada-design.github.io/uikit/master/?path=/docs/visualizations-bar-chart--main
2.  In the image, Y-axis scale is 8000 but graph plotted above Y-axis( Upper scale for Y-axis is more than 8000)
![image](https://user-images.githubusercontent.com/13730428/153242530-fd74f5aa-7ca9-43d3-abc0-a999dbd163cf.png)

### Context 🔦

Not able to check the upper scale for plotted graph.

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by diogofscmariano** [comment]
hi @rajashriDalavi. Thanks for reporting the issue. uikit wraps Plotly charting capabilities, adding on top of this styles from Design System. Everything can be overridden, and it is on the team's side to integrate and change for their needs. We will adjust our sample to cover this case you found, but you have to configure it for your needs ultimately. Clearly this is not a blocker.

**Comment by plagoa** [comment]
I agree, this seems to be a Plotly issue. If we change that specific sample to have the values `[2300, 1000, 9550]` it seems to work and the top tick off the Y axis is displayed correctly:
![image](https://user-images.githubusercontent.com/7498785/153612791-ff8a3354-304c-402d-9587-2a1ddb7eeac2.png)

There are even cases where the top tick is displayed in the Y axis but it doesn't render the corresponding horizontal line (sample values: `[2300, 1000, 8550]`):
![image](https://user-images.githubusercontent.com/7498785/153613093-9582230a-41ca-44c2-9eb3-773ecb0454ad.png)

So I'd say this is the expected Plotly behavior and any changes to the default behavior should be overridden outside of the UI Kit scope.

**Comment by diogofscmariano** [comment]
Hello @rajashriDalavi. Based on @plagoa comments I'm closing this issue. Let us know if you still have any question
