### ISSUE TITLE
In Card view, checkbox `All` not get checked on click.  No event on click  on the `All` checkbox.

### ISSUE THREAD

**Issue by rajashriDalavi** [lumada-design/hv-uikit-react#2668]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

- In Card view, checkbox `All` not get checked on click.  No event on click  on the `All` checkbox.
- It should check all checkbox of the cards as well as on unchecked deselect the checkbox of the cards.
![image](https://user-images.githubusercontent.com/13730428/153247154-4e7b1052-b1c8-45bd-aad9-94085122beb1.png)

### Expected behavior 🤔

- On click it should checked the All checkbox.
- There should be the event on click  on the `All` checkbox.
- It should check all checkbox of the cards as well as on unchecked deselect the checkbox of the cards.

### Steps to reproduce 🕹

Steps:

1. Go to the lumada-design ui toolkit
2. Search for the card view and in Three Views check the `All`. checkbox of the grid view of the cards.
3.
4.

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by diogofscmariano** [comment]
hi @rajashriDalavi. Thanks for reporting the issue. This seems to be an issue with the sample in the documentation, and nothing should block you from building the behavior you need on your side without being blocked. We will fix the sample on our side, and please integrate the feature on your side. If anything does not work please let us know through this ticket.

**Comment by diogofscmariano** [comment]
Hello @rajashriDalavi. A fix for this issue is now available in the latest release. Can you integrate and let us know how it goes?

**Comment by rajashriDalavi** [comment]
Hi @diogofscmariano  Thanks for update. We will plan this in the next sprint. Will update status.

**Comment by plagoa** [comment]
@rajashriDalavi closing this issue as a fix has been released already. Let us know if this is still relevant.
