### ISSUE TITLE
[Dropdown] Unable to search if placed in a HvDialog

### ISSUE THREAD

**Issue by Pedro-Rodrigues30** [lumada-design/hv-uikit-react#2683]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When I place a HvDropdown with search inside a HvDialog, I can't search. 
It appears that the search input is not focused, I'm not able to type anything.

### Expected behavior 🤔

Search should work like it does when I place a HvDropdown without being in a Dialog.

### Steps to reproduce 🕹

Steps:

1. You can check the code in this codesandbox : [Dialog with a searchable Dropdown example](https://codesandbox.io/s/wizardly-greider-1ptm4w?file=/src/App.js)

It's basically a simple dialog with a dropdown example copied from your examples in the Storybook.

### Context 🔦

I'm trying to have a searchable dropdown inside a dialog.

### Your Environment 🌎

Device: Laptop
OS: Windows 10
Browser Edge
Version 98.0.1108.43

**Comment by diogofscmariano** [comment]
hi @Pedro-Rodrigues30. Thanks for reaching out. We will look into this as soon as possible

**Comment by diogofscmariano** [comment]
hello again. After a quick investigation, we found this is an "issue" in the Material UI dialog component. The Dialog forces the focus and prevents other elements outside of the dialog to be focusable. This can be fixed using the prop `disableEnforceFocus` in the HvDialog component like it is described in more detail by its API: https://v4.mui.com/api/modal/
Code sandbox exercising the solution based on what you sent: https://codesandbox.io/s/gallant-bell-bt1qpz
Let us know if you still have an issue.
