### ISSUE TITLE
[SnackbarProvider] - Actions are not clickable 

### ISSUE THREAD

**Issue by andrefrua** [lumada-design/hv-uikit-react#2705]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When using the new SnackbarProvider with actions, those actions aren't clickable, this happens either by sending an action as an ActionGeneric component or using a custom React.Node element.

**Important note:**
This issue seems to be the same as reported [here](https://github.com/iamhosseindhv/notistack/issues/394) and there is a working workaround, by adding this style to the Provider itself:
`style={{ pointerEvents: "all" }}`

### Expected behavior 🤔

We want to be able to click on the actions inside the Snackbar elements

### Steps to reproduce 🕹

Steps:

1. Using UI-KIT storybook, go the file _../packages/core/src/Snackbar/stories/SnackbarProvider.stories.js_
2. On the _SimpleSnackbarSpawner_ add a new action when creating a snackbar, eg:
`enqueueSnackbar(label, {
        variant,
        persist: true,
        snackbarContentProps:
          {
            action: {
              id: "testing",
              label: "BUTTON",
              disabled: false,
            },
            actionCallback: (id, action) => {
              console.log("Testing");
            },
          },
      });`
3. Run storybook
4. Verify that the action button inside the snackbar is not clickable.

### Context 🔦

We are revamping the notification system in the Control Plane and want to use the HvSnackbarProvider wrapper instead of directly using the notistack library.

### Your Environment 🌎

It happens on every environment

**Comment by francisco-guilherme** [comment]
Fixed by #2717
