### ISSUE TITLE
HvTagsInput - limitation of characters on first tag

### ISSUE THREAD

**Issue by hv-carlamartins** [lumada-design/hv-uikit-react#2722]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

We have limitation of characters in this input Tag.
For more than one tag this behaviour doesn't occur.

### Expected behavior 🤔

This limitation shoud not existe.

### Steps to reproduce 🕹

Steps: 

1. Insert the text _@hitachivantara/uikit-react-core_ in Tags Input
 
![image](https://user-images.githubusercontent.com/42973059/161251503-3ca19fd2-0f4e-40d4-852f-277722e62f22.png)

### Your Environment 🌎

Device: [Laptop]
OS: [Windos 10
Browser [chrome]
Version [99]

**Comment by plagoa** [comment]
Closing this issue as this has been fixed in the version 3.62.4 of the uikit-react-core package.
