### ISSUE TITLE
Unable to add bulk actions to <HvAssetInventory />

### ISSUE THREAD

**Issue by MarkJBenson** [lumada-design/hv-uikit-react#2725]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When specifying hasBulkActions in HvAssetIventory e.g. `<HvAssetInventory hasBulkActions />` there doesn't appear to be a way to pass actions to the bulk actions bar.

### Expected behavior 🤔

Should be able to pass actions to the HvAssetInventory e.g. `<HvAssetInventory hasBulkActions bulkActions={actions}` />

### Steps to reproduce 🕹

Steps:

1. Use the `<HvAssetInventory />` component
2. Specify `hasBulkActions`
3. Attempt to specify actions for the BulkActions bar
4.

### Context 🔦

Was attempting to understand the HvAssetInventory bulk actions feature. Was unable to add any items to the built in bulk actions bar.

### Your Environment 🌎

Device: PC
OS: Windows 10
Browser: Edge
Version: 99.0.1150.46
Other details: 
@hitachivantara/uikit-react-core@3.62.0
@hitachivantara/uikit-react-icons@3.8.3
@hitachivantara/uikit-react-lab@3.41.0

**Comment by francisco-guilherme** [comment]
Hi @MarkJBenson, tks for reaching out.

This is effectively an issue with the component.
We are currently working on a more flexible and valuable way of implementing the asset inventory pattern.
The existent one will be soon deprecated so no more work will be done on that.
If this is something critical on your side you are free to contribute with the needed fix.

Stay tuned 👍
