### ISSUE TITLE
`HvQueryBuilder` allows for query groups to be added when `maxDepth={0}`

### ISSUE THREAD

**Issue by zettca** [lumada-design/hv-uikit-react#2758]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When I create an `HvQueryBuilder` with `maxDepth={0}`, although the "Add button" group disappears, the "create condition group" "link button" still allows to create a group.
```tsx
<HvQueryBuilder attributes={attributes} maxDepth={0} />
```

<img width="951" alt="image" src="https://user-images.githubusercontent.com/638946/165946315-791cc19e-8c07-4e00-a67a-11fcb3ae9e2f.png">

### Expected behavior 🤔

Not being able to create a query group (i.e. label is "Create a condition~ or condition group~)

### Steps to reproduce 🕹

Steps:

1. Create `<HvQueryBuilder attributes={attributes} maxDepth={0} />`
2. Click the create "condition group" button
3. Notice how it creates a group, when it shouldn't

### Your Environment 🌎

Chrome on MacOS 11.6

**Comment by plagoa** [comment]
Closing this issue. This has been fixed as of version `@hitachivantara/uikit-react-lab@3.45.4`.
