### ISSUE TITLE
`HvQueryBuilder` doesn't allow configuring styles via `classes` object

### ISSUE THREAD

**Issue by zettca** [lumada-design/hv-uikit-react#2759]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

`HvQueryBuilder` internally has a `classes` object for styling. This object isn't exposed as a prop, making it harder to style the component.
More specifically, I would like to configure the `topRemoveButton`, which has a `backgroundColor` that needs to match the page's `backgroundColor`:

<img width="905" alt="image" src="https://user-images.githubusercontent.com/638946/165948793-0648e88e-9505-423f-a17c-b9f8a05fe7f6.png">

### Expected behavior 🤔

Being able to configure `HvQueryBuilder`'s classes, similarly to other components, such as:

```tsx
<HvQueryBuilder attributes={attributes} classes={{ topGroup: myClassA, topRemoveButton: myClassB }} />
```

### Steps to reproduce 🕹

Steps:

1. Try styling component with <HvQueryBuilder classes={{ topRemoveButton: "a" }} />
2. Doesn't work.

### Your Environment 🌎

Chrome on MacOS

**Comment by francisco-guilherme** [comment]
Hi @zettca,

You can find all the requests made in the latest release [3.45.6](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-lab%403.45.6)

Let me know if  works for you.

tks

**Comment by zettca** [comment]
> 

Hey, thanks!

I didn't have the time to upgrade and test yet, but I noticed that [`classes` isn't typed](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/lab/src/QueryBuilder/QueryBuilder.d.ts#L6).

`RuleGroup` isn't typed; but that doesn't really matter to us as we're not using it directly.

**Comment by plagoa** [comment]
@zettca a fix for the missing typings for the `classes` object has been merged and should be available in the next release.
