### ISSUE TITLE
Add background to tabs and breadcrumb menus

### ISSUE THREAD

**Issue by laura-pentaho** [lumada-design/hv-uikit-react#2770]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When scrolling there's an overlap:

![image](https://user-images.githubusercontent.com/24935496/167461738-1561cc2f-df30-4ef6-bb42-1eb3861f03fe.png)

![image](https://user-images.githubusercontent.com/24935496/167461783-0bc5812d-69b0-4617-802f-087014e9d729.png)

![image](https://user-images.githubusercontent.com/24935496/167461822-ef2ef926-11cc-4818-92c2-d113b408b33a.png)

### Expected behavior 🤔

All labels should be readable.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by francisco-guilherme** [comment]
Hi @laura-pentaho, tks for reaching out.

Hi understand this overlap looks strange but its the default components behaviour.
I will try to scale this to DS on my side and ask for a possible solution.

in the meantime did you try to override the background specs?

Tks

**Comment by laura-pentaho** [comment]
Hi,

We didn't, but we may try to use the background from the main page and see how it works.

Thanks

**Comment by francisco-guilherme** [comment]
Hi @laura-pentaho,

Talked with DS reps and they didn't find any problem to override the background specs if you need.
Let me know if it worked for you.

**Comment by laura-pentaho** [comment]
It worked:
![image](https://user-images.githubusercontent.com/24935496/170694744-1ffe3d4d-1eb3-4ec5-9908-71008558c6bf.png)
![image](https://user-images.githubusercontent.com/24935496/170694780-f25a0d86-8901-4747-a92e-856601c5cda3.png)
