### ISSUE TITLE
Barchart sometimes breaks when the page is loading

### ISSUE THREAD

**Issue by rubenbarroshv** [lumada-design/hv-uikit-react#2774]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When the page is loading the component Barchart executes the function recalculateBarWidth, and sometimes this
ref.current.el.getBoundingClientRect().width returns 0. This leads to an infinite loop inside the page where it executes setChartData with the MIN_BAR_WIDTH and the undefined width (the 2nd and 3rd if's).

### Expected behavior 🤔

Prevent the page loop and breaking.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

We need to change the code so that this ref.current.el.getBoundingClientRect().width returns 0.

### Your Environment 🌎

Device:Laptop
OS: MacOS Monterrey 12.3.1
Browser Chrome
Version 101
Other details 1920x1080

**Comment by francisco-guilherme** [comment]
Hi @rubenbarroshv tks for reaching out,

Bux fixed and released in(uikit-react-core@3.67.3)[https://github.com/lumada-design/hv-uikit-react/compare/@hitachivantara/uikit-react-core@3.67.2...@hitachivantara/uikit-react-core@3.67.3]
