### ISSUE TITLE
`HvTable` not working on Next.js

### ISSUE THREAD

**Issue by urkopineda** [lumada-design/hv-uikit-react#2779]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When including a `HvTable` on a Next.js page, it throws a server error of "`document` is not defined".

<img width="992" alt="Screenshot 2022-05-20 at 18 02 15" src="https://user-images.githubusercontent.com/9933709/169567501-fa4278e3-5500-4b1f-bebb-f220b5c8ac89.png">

### Expected behavior 🤔

It should just work.

### Steps to reproduce 🕹

Steps:

1. Include a simple `HvTable`.
2. It fails.

PS: [Here](https://codesandbox.io/s/hv-uikit-next-js-hvtable-not-working-tj1x4c?file=/src/pages/_app.tsx) is a CodeSandbox with the issue.

### Context 🔦

We are trying to render a list of data fetched using SWR on Next.js.

### Your Environment 🌎

Device: Laptop / MacBook Pro
OS: macOS Monterey v12.4
Browser: Microsoft Edge 
Version: 101.0.1210.53 (Official build) (arm64)

**Comment by zettca** [comment]
Are you sure it's just the `HvTable` component? 🤔 
With the sample you provided I get the following error, even if I remove `HvTable` from it.

```
error - node_modules/@hitachivantara/uikit-react-core/dist/modern/BaseDropdown/BaseDropdown.js (263:57) @ eval
ReferenceError: document is not defined
```

**Comment by francisco-guilherme** [comment]
Hi @urkopineda  and @zettca , tks for your feedback.

As you know the support for Next.js is still experimental and our initial focus was just to unblock teams trying to work with it.
Until is fully supported by us, it's pretty natural that some of these issues will arise.
Is you are really invested on using Next.js we will rely on your feedback to identify them.

Regarding the specific issue identified, for now, unless you want to contribute with the solution for it 🤔, the best way to deal with it is to use Dynamic Imports without SSR enabled. 
Please take a look at this [sandbox](https://codesandbox.io/s/hv-uikit-next-js-hvtable-not-working-forked-l3dz0f?file=/src/pages/projects/index.tsx:0-1311) and let me know if it works for you.

Tks

**Comment by urkopineda** [comment]
Hi @zettca @francisco-guilherme ,

Yes, it works if we force the table to just render on client side, I just wanted to let you know that the table was not working on Next.js.

Regards,

Urko
