### ISSUE TITLE
FilterGroup repeats first label name to all filters

### ISSUE THREAD

**Issue by rubenbarroshv** [lumada-design/hv-uikit-react#2797]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When using the FilterGroup component, every filter label has the label from the first filter.

### Expected behavior 🤔

When using the FilterGroup Component, each filter should have its own label, instead of the first filters label.

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/youthful-goldwasser-79opf5?file=/src/App.js
2. When using version 3.62.6 (FilterGroup should work as expected) 
3. When using version 3.66.2 (FilterGroup repeats the first filter label to all filters)

### Context 🔦

Somewhere between versions 3.62.6 - 3.66.2, something might have changed underneath the FilterGroup component that breaks it, and it might be breaking some other component.

### Your Environment 🌎

Device: Laptop
OS: macOS Monterrey 12.3.1
Browser chrome
Version 102

**Comment by rubenbarroshv** [comment]
after some more debugging, the component breaks at version 3.65.0

**Comment by francisco-guilherme** [comment]
According to @eliofreitas and @HQFOX this is related with a "react-scripts" update.
Downgrading to 4.0.2 should work.

Tks
