### ISSUE TITLE
Hitachi Vantara UI Kit Issues With React Markdown

### ISSUE THREAD

**Issue by prajwalkumar9** [lumada-design/hv-uikit-react#2800]
### Discussed in https://github.com/lumada-design/hv-uikit-react/discussions/2791

In our project we are using the latest version of react-markdown 
https://www.npmjs.com/package/react-markdown

But when we are using the Hitachi Vantara React UI Kit Lab Component for Table (https://lumada-design.github.io/uikit/master/?path=/docs/lab-table--main) its giving issues on deployment and the pages are not loading and resulting in errors in console.

Can you guys please check on this integration and help us in resolving this issue. It is working fine with the old react markdown package version 4.3.1 but issue persists in all the latest version of react markdown (Tried 8.0.3, 8.0.2, 8.0.1)
</div>

**Comment by francisco-guilherme** [comment]
Hi @prajwalkumar9 , still facing this issue?

**Comment by prajwalkumar9** [comment]
Did you do anything from your side to fix this issue?  We need to upgrade the react markdown package and see if its resolved. Will give it a try and let you know on this. Meanwhile we are using a old version of react-markdown. Thanks

**Comment by francisco-guilherme** [comment]
Hi @prajwalkumar9, 

Here is a [codesandbox](https://codesandbox.io/s/hv-uikit-next-js-markdown-dp4q1f?file=/src/pages/projects/index.tsx) with the use case you presented.

I'll close this issue for now.
If you still face any issue please provide an example showcasing it and reopen the issue.

Tks
