### ISSUE TITLE
`corejs@2` peer-dependency potentially "cause a slowdown up to 100x"

### ISSUE THREAD

**Issue by zettca** [lumada-design/hv-uikit-react#2807]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When running `npm ci` in my project, I'm getting the following warning:
```
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

This is caused by `rc-tooltip@3`, a dependency recently added to `@hitachivantara/uikit-react-core`.

### Expected behavior 🤔

`npm i` installs without `core-js@2` slowdown warning

### Steps to reproduce 🕹

Steps:

1. `npm install` (on a project with `@hitachivantara/uikit-react-core@3.67.0` or later)
2. See the warning in the output logs

### Context 🔦

- `rc-tooltip@3` was released almost 4 years ago.
- `rc-slider@10` was also also added in the same UI-Kit release as `rc-tooltip`, which uses `rc-tooltip@5`.
  - there are currently 2 `rc-tooltip` major versions in use

**Comment by plagoa** [comment]
@zettca thanks for pointing this out. I opened a PR with a fix for it and should be available in the next release.

**Comment by plagoa** [comment]
Fixed on version [@hitachivantara/uikit-react-core@3.67.12](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%403.67.12)
