### ISSUE TITLE
`HvQueryBuilder` is using a deprecated `HvTimePicker`

### ISSUE THREAD

**Issue by zettca** [lumada-design/hv-uikit-react#2810]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When using `HvQueryBuilder` and creating a date/time condition, I get the following warning in the console:

> TimePicker is deprecated. Please use the TimePicker component in Core

### Expected behavior 🤔

`HvQueryBuilder` using `HvTimePicker` from the `core` library and not getting this warning

### Steps to reproduce 🕹

Steps:

1. Instantiate an `HvQueryBuilder`
2. start selecting a condition of type date
3. notice the error

### Context 🔦

https://github.com/lumada-design/hv-uikit-react/blob/master/packages/lab/src/QueryBuilder/Rule/Value/DateTimeValue/DateTimeValue.js#L9-L10

**Comment by francisco-guilherme** [comment]
Hi @zettca, this is a bug and is being addressed by the team.

Tks

**Comment by plagoa** [comment]
This has been fixed and released. Closing the issue now.
