### ISSUE TITLE
`@hitachivantara/uikit-react-lab` not working for Next.js

### ISSUE THREAD

**Issue by urkopineda** [lumada-design/hv-uikit-react#2834]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

We have implemented the lab package on a Next.js project. We are trying to use the `HvProgressBar` component but, when rendering, we get the next error message:

<img width="982" alt="Screenshot 2022-07-06 at 08 06 12" src="https://user-images.githubusercontent.com/9933709/177480344-73b8630b-0fe1-4915-81fa-43b6c1db667d.png">

### Expected behavior 🤔

It should work.

### Steps to reproduce 🕹

Steps:

1. On a Next.js project, try to render a simple `HvProgressBar`.

### Your Environment 🌎

Device: MacBook Pro
OS: macOS 12.4
Browser: Microsoft Edge
Version: 103.0.1264.44

**Comment by francisco-guilherme** [comment]
Hi @urkopineda , tks for reaching out.

We are tackling that issue on our current sprint.
I'll let you know when is solved.

Tks

**Comment by francisco-guilherme** [comment]
Hi @RomanShmyhelskyi, when you can please test it with out latest version.
It should now work with any framework that supports SSR (NextJS, remix ...)
There might be some components that are not compatible yet, but those can be dynamically imported for now.
