### ISSUE TITLE
Autofocus feature for HvDropdown

### ISSUE THREAD

**Issue by wojciechpajor** [lumada-design/hv-uikit-react#2845]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Summary 💡

HvDropdown element lck autoFocus atribute like in for ex. HvInput to focus on dropdown on render

### Motivation 🔦

This feature would be very helpfull for making intuitive layouts

**Comment by francisco-guilherme** [comment]
Hi @wojciechpajor, tks for reaching out.

We'll refine this internally and when prioritised i'll let you know.

**Comment by francisco-guilherme** [comment]
This issue was closed because it has been inactive.
