### ISSUE TITLE
Consistent Select All Behaviour

### ISSUE THREAD

**Issue by AJDowdsHV** [lumada-design/hv-uikit-react#2854]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Summary 💡

There seems to be some inconsistency in the effect of pressing the `select all` button between the `table/bulk actions` and `dropdown`.

On the table / bulk actions, when some rows are selected and the `- x/y` button is pressed, all visible rows (on the current page) are then selected. In the dropdown, if we select some options and then press the `- x/y` button, all options are deselected.

The behaviour on the table is as we would expect but the dropdown isn't. Ideally we would actually not have the `- x/y` button at all on the dropdown and instead the top button would consistently stay as `All`, if some options were selected and it was clicked, it would populate the remaining options (i.e. all would be selected) and if it was clicked when all options were selected, it would deselect everything.

### Examples 🌈

![SelectAll](https://user-images.githubusercontent.com/105852608/179722320-559bf46e-425a-4878-a1ca-34b646fb9731.gif)

### Motivation 🔦

![image](https://user-images.githubusercontent.com/105852608/179722483-a24fe105-4ae1-41a0-8a25-8017e19a94e0.png)

- Consistent behaviour between the components (lab table / bulk actions and dropdown)
- Preferably that the dropdown `- x/y` button would remain as an `all` button

**Comment by francisco-guilherme** [comment]
Hi @AJDowdsHV, tks for reaching out.

We'll refine this internally and when prioritised i'll let you know.

**Comment by plagoa** [comment]
Hello @AJDowdsHV , the consistency on the "Select All" behavior should be fixed as of version 5.36.11 of the `core` package.
