### ISSUE TITLE
As a UI Kit user, I don't want components' inner `key` logic to be exposed to me

### ISSUE THREAD

**Issue by zettca** [lumada-design/hv-uikit-react#2873]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Summary 💡

Currently, some UI Kit components that `.map` children have their children's `key` coupled to an optional user passed `id` prop. As a UI Kit user using a "widget" component (whose sub-components aren't exposed to me), I don't want to have to worry about that logic that is hidden from me.

If I don't pass an `id` (or sometimes even a `key`) to the components, they might not get a unique `key` (or `key` at all), making the component unstable.

### Examples 🌈

In a typical scenario, `myItems` comes from an API or pre-defined struct somewhere.
Ideally, I would be able to pass `myItems` directly to the component, or with the minimal mapping/renaming changes:

For example:
```tsx
myItems.map((item, index) => ({
  label: item.name,
  disabled: item.active
}));
```

```tsx
<List items={myItems} />
<Dropdown items={myItems} />
```

If in the `map` above I need to pass an `id`, for a reason that isn't explained to me and `myItems` doesn't already include, I would be tempted to just add the `index` or maybe even `name`, which are both bad `key`s (ie. I might have multiple `List` on that page - internal `ListItem` would get duplicate `key`).

AFAIK, the following components have this or similar problems:

- CardView
- ListView
- MultiButton
- FileUploader
- QueryBuilder

but there might be more

### Proposal 🔦

The goal here is to have:

- A user that doesn't need to worry about `key`s or `id`s in the `ComponentX` that hide their sub-components
- `ComponentX`'s sub-components have unique, stable `key`s

I'm not sure if this would be a one-size-fits-all solution for this, but I think `useUniqueId` could be leveraged to achieve this.

```tsx
const id = useUniqueId(idProp, "componentX");

items.map((item, idx) => <Item key={setId(id, idx)} />)
```

If the user passes an `id` to `ComponentX`, good. If not, that's not a problem because `useUniqueId` will create one.

**Comment by francisco-guilherme** [comment]
Hi @zettca,

We partially agree with your approach, but it's not clear the right solution for us.
We'll refine this internally and when prioritised i'll let you know.
In the meantime we'll close #2870.

Tks

**Comment by francisco-guilherme** [comment]
HI @zettca, take a look at #2883

**Comment by zettca** [comment]
#2883 doesn't address the `key` issue, it changes the component's internal `id`.

I'll leave some comments in the PR
