### ISSUE TITLE
Bug when showing multiple tooltips (HvTooltip)

### ISSUE THREAD

**Issue by stephaniegaspar** [lumada-design/hv-uikit-react#2890]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

I'm creating a new component called HvStepNavigation and I use HvTooltip to display a tooltip on each step component. I noticed that when the mouse is hovering and leaving some of the steps, the tooltip remains open after leaving. This behavior happens more often on the "current" step.

<img width="957" alt="tootlipIssue" src="https://user-images.githubusercontent.com/108751625/184183467-47c0b64d-1f31-416b-a279-f0c2807bbca2.png">

### Expected behavior 🤔

The tooltip is expected to be closed on every mouse leave event.

### Steps to reproduce 🕹

Steps:

1. Checkout on branch [stephaniegaspar:MLAAS-1494](https://github.com/stephaniegaspar/hv-uikit-react-step-navigation/tree/MLAAS-1494) and run the project
2. Access StepNavigation menu option on left section
3. Go to the "With Tooltip" section of StepNavigation page and hover every dot displayed on the component with your mouse until you find a wrong behavior

### Context 🔦

This issue doesn't have a meaningful impact. At least, only affects sometimes the User Experience interaction.

### Your Environment 🌎

Device: Laptop
OS: Windows 10 Enterprise
Browser Chrome
Version 104

**Comment by francisco-guilherme** [comment]
Hi @stephaniegaspar, is this something still relevant?

**Comment by stephaniegaspar** [comment]
Hi @francisco-guilherme,
At the time, I used a custom hook `withTooltip` from ui-kit-core and then I replaced it with the component `HvTooltip` and the problem wasn't persistent. So I believe that the hook `withTooltip` should be revised properly.

**Comment by francisco-guilherme** [comment]
Tks, for the feedback. Closing the issue for now.
