### ISSUE TITLE
After Upgrading @hitachivantara/uikit-react-core package from 3.75.0 to 4.0.4

### ISSUE THREAD

**Issue by chandinigangupalli** [lumada-design/hv-uikit-react#2949]
1. After upgrading  from 3.75.0 to 4.0.4  we are getting below mentioned error

![image](https://user-images.githubusercontent.com/114911122/196938716-a602ab1a-1978-44f4-bd5d-7ed1b51fe37c.png)

2. After removing this deprecated property disableBackdropClick we are getting console errors and the pages are not loading wherever we are using Hvdialog component.

![image](https://user-images.githubusercontent.com/114911122/196939625-a4805df8-50bf-4923-8dd5-3b9ac40b1872.png)

**Comment by plagoa** [comment]
The `disableBackdropClick` was deprecated in Material UI v5, but we kept that functionality on our side to maintain compatibility with v3 Dialogs:
https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/Dialog/Dialog.js#L33

But looking at the error on the second image, it doesn't seem to be related. It seems to be throwing an error trying to read the `typography` prop on the styles file, which might mean that it's not generating the theme correctly (the `typography` prop exists in `theme.hv`). 

Did you follow the migration guide here:
https://lumada-design.github.io/uikit/master/?path=/docs/introduction-migration-from-v3-x--page

*Section*: Adjust theme definition.

**Comment by francisco-guilherme** [comment]
@chandinigangupalli we'll close this issue for now. Please feel free to reopen it if needed.
