### ISSUE TITLE
Characters "_" or "-" aren't displayed on listRoute.label prop of HvBreadCrumb

### ISSUE THREAD

**Issue by stephaniegaspar** [lumada-design/hv-uikit-react#2960]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

On the following sample case:
`<HvBreadCrumb listRoute=[{label: "_something-", path: "/"}] />`,  the label of the first element defined on `listRoute` will appear "something", not "_something-".

### Expected behavior 🤔

Should appear "_something-".

### Steps to reproduce 🕹

Steps:

1. Go to [lumada-ml-model-management-ui-app](https://dev-mlaasdev.hitachi-lumada.io/hitachi-solutions/lumada-ml-model-management/lumada-ml-model-management-ui-app/projects/5d960d27-815e-4523-a57a-63ff3e61f5e5/models/b094dc72-f5dc-446c-aaeb-d0d9b613c350)
2. Notice that HvBreadCrumb is rendered with no text, and it should be rendered like _______ > _

![image](https://user-images.githubusercontent.com/108751625/200371187-8f5c775f-2937-4140-8e68-d6ab0736482c.png)

### Your Environment 🌎

Device: Laptop
OS: Windows 10
Browser: Chrome 
107.0.5304.88

**Comment by francisco-guilherme** [comment]
Hi @stephaniegaspar, tks for reaching out.

I don't recall the reason behind this behaviour, but your requirement seems to make sense.
We'll refine this internally and move to our backlog once prioritised.

Is this something critical on your side? If so, do you have the time to contribute with the fix?

**Comment by stephaniegaspar** [comment]
Hi @francisco-guilherme,
In our side, the issue is still on backlog but I have time to fix it.
If you already created the issue on your backlog, you can assign it to me.

**Comment by francisco-guilherme** [comment]
If you have the time, please go ahead with the fix. It would be very helpful.

**Comment by stephaniegaspar** [comment]
Okay 👍

**Comment by stephaniegaspar** [comment]
https://github.com/lumada-design/hv-uikit-react/pull/2986
