### ISSUE TITLE
`useTheme` returns null

### ISSUE THREAD

**Issue by andyjansson** [lumada-design/hv-uikit-react#2972]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

After migrating to v4 from v3, `useTheme` from `@mui/styles` returns null. The reason seems to be the fact that [Provider relies on `@mui/material`](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/Provider/Provider.js#L13), which does not rely on JSS, while `@mui/styles` do. Switching to `@mui/material/styles` does make the theme load, but then it complains about `hv` not being found.

**Comment by plagoa** [comment]
@andyjansson can you check the migration guide and see if it helps? 

https://lumada-design.github.io/uikit/master/?path=/docs/introduction-migration-from-v3-x--page

See section **Adjust theme definition**.

**Comment by francisco-guilherme** [comment]
Hi @andyjansson, is that a TS error?

Dis you check the [Adjust theme definition](https://lumada-design.github.io/uikit/master/?path=/docs/introduction-migration-from-v3-x--page ) section?

**Comment by andyjansson** [comment]
Again, yes, I've been following everything in the migration guidelines, but it's broken. Please, go on and validate your own guide with your adoption repo: It does not work.
