### ISSUE TITLE
Issue In Unit Tests When we upgrade @hitachivantara/uikit-react-core from 3.75.0 to 4.3.1

### ISSUE THREAD

**Issue by prajwalkumar9** [lumada-design/hv-uikit-react#3017]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

When i upgrade the @hitachivantara/uikit-react-core component from 3.75.0 to 4.3.1 the application builds and runs successful but the unit tests is giving error.

![image](https://user-images.githubusercontent.com/106602044/207594172-0913783e-4cec-4ef0-9bb0-80851ab9499d.png)

I have used the HVProvider Component as in the screenshot below from the component.

![image](https://user-images.githubusercontent.com/106602044/207594465-793d1474-9dcb-49ce-aed7-03617afa7d2a.png)

Also i have used the HVProvider in the unit test file as below.

![image](https://user-images.githubusercontent.com/106602044/207594666-3e741c95-a98d-43d7-b838-e1e66ab5c63e.png)

Can you please suggest. as per this migration document (https://lumada-design.github.io/uikit/master/?path=/docs/introduction-migration-from-v3-x--page) i have already installed @mui/material @mui/styles and @emotion/react @emotion/styled, Uninstalled npm uninstall @material-ui/*.

### Expected behavior 🤔

Unit Tests needs to be run without fail

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by francisco-guilherme** [comment]
Hi @prajwalkumar9, thanks for reaching out,

It seems to be a TS error.

Did you check the [Adjust theme definition](https://lumada-design.github.io/uikit/master/?path=/docs/introduction-migration-from-v3-x--page ) section?
