### ISSUE TITLE
Support new `appDir` experimental feature of Next.js 13

### ISSUE THREAD

**Issue by urkopineda** [lumada-design/hv-uikit-react#3023]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Summary 💡

It would be nice if the UI Kit could support new Next.js 13 `appDir` experimental feature, which uses React 18 to render server side components.

### Examples 🌈

I've created a repo for testing this functionality here: https://github.com/urkopineda/nextjs-13-app-dir-ui-kit-example

Currently when setting the ´HvProvider´ fails with the next error message:
<img width="994" alt="Screenshot 2022-12-16 at 19 08 11" src="https://user-images.githubusercontent.com/9933709/208162638-580f6b23-c4f0-49d5-ab8c-4a7a8a782122.png">

### Motivation 🔦

Supporting the new `appDir` feature of Next.js 13 will help us using UI Kit with the new layout system and the powerful server side components of React 18.

**Comment by francisco-guilherme** [comment]
Hi @urkopineda thanks for reaching out,

We are not planning on supporting/ looking at this until feb/ march this year.
If you have the time feel free to contribute with the possible changes needed.

Anyway, the error you identified seems to be the lack of core-js dependency. Did you try to install it?

Tks

**Comment by francisco-guilherme** [comment]
Hi @urkopineda , i'll close this issue for now, as the usage of the UI Kit with Nextjs is unblocked for now,, but we don't foresee to invest much more on this in the near future.
