### ISSUE TITLE
Need help to create multi level dropdown menu

### ISSUE THREAD

**Issue by Madhura-A-M** [lumada-design/hv-uikit-react#3142]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Current behavior 😯

Hi team, we need to create a multi level Dropdown menu for one of our functionality. We could not find any relevant documentation in lumada link(https://lumada-design.github.io/uikit/master/?path=/docs/inputs-dropdown-dropdown-menu--main ), could you please suggest on the same.
The UI should look like below

On click of Actions button Dropdown menu should open, on click of Notes, submenu should open like below.
![image](https://user-images.githubusercontent.com/125947184/220253632-2ba9dcaa-c906-40fa-ad3c-d79a8755c14d.png)

### Expected behavior 🤔

We need to have multi level dropdown menu or please suggest a suitable component to handle this.

### Steps to reproduce 🕹

Steps:

1. On click of Actions button in the above image Dropdown menu should open with 6 options
2.On click of one of the option, Notes one more Dropdown menu(Submenu) should open with 2 options 'Application Notes' and 'Release Notes'

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by zettca** [comment]
Hello @Madhura-A-M, sorry for the delayed answer.

UI Kit currently does not support "nested" Dropdown menus - and as neither does our NEXT Design System, we do not plan on supporting it.

The mock you've shown seems to not be using NEXT either way. You can use an external library (ie [`react-nested-dropdown`](https://github.com/g-makarov/react-nested-dropdown)) to implement that use case
