### ISSUE TITLE
Allow the possibility to have an <A> element with button style's

### ISSUE THREAD

**Issue by hugo-jose** [lumada-design/hv-uikit-react#3229]
### Latest version

- [X] I have tested the latest version

### No Hitachi Vantara confidential content

- [X] I'm not including any Hitachi Vantara confidential content

### Summary 💡

Using UIKit 5, it's not possible to create an <A> element with the button style.

### Motivation 🔦

This is important for accessibility purpose, to allow the correct usage of <A> instead of buttons.

Redefining/copy button style for new components/apps don't seems to me as a correct approach.

**Comment by plagoa** [comment]
Story: https://hv-eng.atlassian.net/browse/HVUIKIT-6728

**Comment by MEsteves22** [comment]
This has been added in [5.9.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.9.0).
