### ISSUE TITLE
HvDropdown does not have border when opening upwards

### ISSUE THREAD

**Issue by wojciechpajor** [lumada-design/hv-uikit-react#3296]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

![image](https://user-images.githubusercontent.com/42919552/234543551-e5a6011b-3758-4771-9136-ceb515feefcb.png)

### Expected behavior 🤔

im expecting border on top part of opened dropdown

### Steps to reproduce 🕹

Steps:

1.open dropdown that is opening upwards
2.
3.
4.

### Your Environment 🌎

Device: Laptop
OS: windows 10
Browser chrome

**Comment by plagoa** [comment]
This issue has been fixed and is available in the latest release of v5. 

![image](https://github.com/lumada-design/hv-uikit-react/assets/7498785/45d23f89-5a79-4cc3-aed1-a5737d0aefa2)
