### ISSUE TITLE
HvDialog - blinking background and icon color

### ISSUE THREAD

**Issue by brunonovaishv** [lumada-design/hv-uikit-react#3314]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

- When the `HvDialog` component renders the background properties change (opacity and transition) and this causes a visual effect of the background blinking.
- When using the `HvFileUploader `component inside of `HvDialog`, and after successfully uploading a file, the checkmark icon has the color `--uikit-colors-secondary` (grey color)

### Expected behavior 🤔

- The background of `HvDialog` component shouldn't have that visual effect while render occurs.
- When using the `HvFileUploader `component inside of `HvDialog`, and after successfully uploading a file, the checkmark icon should have the color `--uikit-colors-positive` (green color)

### Steps to reproduce 🕹

Steps:

1. Use a `HvFileUploader` inside of `HvDialog`
2. Upload a file
3. Wait for the file to be successfully uploaded to see the checkmark icon

### Your Environment 🌎

Device: Laptop
OS: Ventura 13.3.1
Browser: chrome
Version: 113.0

**Comment by plagoa** [comment]
@brunonovaishv this has been fixed on [@hitachivantara/uikit-react-core@5.7.4](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.7.4)
