### ISSUE TITLE
VerticalNavigation - Slider mode - When opening the panel the initial menu displayed should be the one with the selected item

### ISSUE THREAD

**Issue by andrefrua** [lumada-design/hv-uikit-react#3320]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When using the VerticalNavigation component in slider mode, the initial panel displayed should be the one with the selected item. Currently it will display the first level of menu items. This can be seem in storybook "Vertical Navigation - Slider Mode" example:

![image](https://github.com/lumada-design/hv-uikit-react/assets/26412841/8f21623d-55f9-4cd0-bbff-5a4a2c2ae088)

### Expected behavior 🤔

Using the same storybook example. The behavior should be to display the panel with the selected element when first opening the navigation. Using the same Storybook example it should open like this:

![image](https://github.com/lumada-design/hv-uikit-react/assets/26412841/77139c7b-d552-4dd1-99fd-864db15cfe00)

### Steps to reproduce 🕹

Steps:

1. Open Storybook
2. Go to "Vertical Navigation -> Slider Mode" example
3. Check that the panel displayed is not the one where the selected item is

### Context 🔦

We are currently implementing the responsiveness feature on the App Shell and this is not the desired behavior.

**Comment by plagoa** [comment]
This is available [@hitachivantara/uikit-react-core@5.11.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.11.0)
