### ISSUE TITLE
Vertical Navigation - Slider Mode - The first level of item shouldn't display the Header

### ISSUE THREAD

**Issue by andrefrua** [lumada-design/hv-uikit-react#3321]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

According to the Design System pattern, when displaying the first level of items in the Vertical Navigation in Slider Mode the header shouldn't be displayed as it currently is:

![image](https://github.com/lumada-design/hv-uikit-react/assets/26412841/1be7fa7d-8381-458b-82ca-88c5c3707c39)

### Expected behavior 🤔

There should be no header when in the first level of items. This is what it should look like according to DS:

![image](https://github.com/lumada-design/hv-uikit-react/assets/26412841/2a478891-18c1-4247-b224-f39afbe591fd)

### Steps to reproduce 🕹

Steps:

1. Open Storybook
2. Go to "Vertical Navigation -> Slider Mode" example
3. Check that the first level of items is displaying the Header

### Context 🔦

On the App Shell side we need to have this compliant with the DS specifications.

**Comment by plagoa** [comment]
@andrefrua we're going to clarify this with the DS team.
