### ISSUE TITLE
HvDatePicker - not able to set custom error message, UIKIT always display 'Invalid date' as error message

### ISSUE THREAD

**Issue by kterasawa-hv** [lumada-design/hv-uikit-react#3370]
### Which version of NEXT UI Kit are you opening this bug for?

v3.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

- Cannot set different error message
- UIKIT always display default message of "Invalid date" as error message
- P.S: UIKIT team confirmed that currently does not support (May 17, 2023) on UIKIT slack channel 

![image (1)](https://github.com/lumada-design/hv-uikit-react/assets/74368886/1297eb0f-8041-452b-ba13-b25bbbb24350)

### Expected behavior 🤔

- Able to set different error message 

### Steps to reproduce 🕹

Enter sandbox link: 

And/or the steps to reproduce:

1.
2.
3.
4.

### Context 🔦

- Able to display different language error message to support internationalization 

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by zettca** [comment]
Hello @kterasawa-hv, thanks for opening the issue 👋

This is a bug, as the "Invalid date" is hard-coded. We'll look into it

**Comment by HQFOX** [comment]
Hello @kterasawa-hv, a v3 release has been made with the [fix](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%403.75.1).
thanks for opening the issue.
