### ISSUE TITLE
FilterGroup counter problem

### ISSUE THREAD

**Issue by rubenbarroshv** [lumada-design/hv-uikit-react#3388]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

There is a problem while using the FilterGroup that when we Clear Filters, and then we select a filter, the Counter remains at 0.

### Expected behavior 🤔

The Counter should update accordingly to the number of filters selected.

### Steps to reproduce 🕹

Enter sandbox link: https://lumada-design.github.io/uikit/master/?path=/docs/widgets-filter-group--main

And/or the steps to reproduce:

1. Open Filters
2. Clear Filters + Apply
3. Open Filters
4. Select Sub-Sub-Category Category Cat.. + Select Sub sub Category 2 + Apply
5. Verify that the Counter remains at 0

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by zettca** [comment]
Fix released in [`@hitachivantara/uikit-react-core@5.12.0`](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.12.0)
