### ISSUE TITLE
Duplicated alert role in snackbar notification in snackbar provider scenario

### ISSUE THREAD

**Issue by VGervasio** [lumada-design/hv-uikit-react#3428]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When looking at snackbar provider sample (https://lumada-design.github.io/uikit/master/?path=/docs/components-snackbar-provider--snackbar-provider) we can see that for each notification the role alert appears twice:
![image](https://github.com/lumada-design/hv-uikit-react/assets/14977550/5b317a4b-1ece-4b1c-8200-7bfb6e2863f4)

### Expected behavior 🤔

Each snackbar notification has only one element with role alert.

### Steps to reproduce 🕹

Steps to reproduce:

1. Go to https://lumada-design.github.io/uikit/master/?path=/docs/components-snackbar-provider--snackbar-provider
2. Create a snackbar and inspect it.
3. More than one element has the role alert.

### Context 🔦

This does not seem correct and has an impact in automation tests for example when checking the number of visible notifications.

**Comment by plagoa** [comment]
Bug opened: https://hv-eng.atlassian.net/browse/HVUIKIT-6751

**Comment by MEsteves22** [comment]
Hello 👋

Thank you for opening this issue, this was fixed on [5.18.1](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.18.1).
