### ISSUE TITLE
[Breadcrumb] Label removing symbols

### ISSUE THREAD

**Issue by HQFOX** [lumada-design/hv-uikit-react#3470]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When creating a label for the Breadcrumb component any symbols like parentheses or ampersand will be removed.

### Expected behavior 🤔

The expected behavior  is to keep the symbols.

### Steps to reproduce 🕹

Steps to reproduce:

1. Add label with symbol to a breadcrumb component
2. See the label

**Comment by zettca** [comment]
Reopening this as this fix led to unexpected issues in Applitools

**Comment by MEsteves22** [comment]
Hello 👋

Thank you for opening this issue. This was fixed on [5.18.5](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.18.5).
