### ISSUE TITLE
[Breadcrumb] Label capitalizing first letter

### ISSUE THREAD

**Issue by aanjum154** [lumada-design/hv-uikit-react#3471]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

If a label contains lowercase letters and if this label is the last one to be displayed in the breadcrumb, the first letter in the label gets capitalized as shown below:
![image](https://github.com/lumada-design/hv-uikit-react/assets/138006767/d15059bd-f53c-4cc2-9546-314f1221f971)

 If the same label is displayed last but one, it gets displayed as shown below and this is the expected behavior:
![image](https://github.com/lumada-design/hv-uikit-react/assets/138006767/f17e067d-7964-425a-bbf3-a42ee0bf6552)

### Expected behavior 🤔

Label should be displayed as it is without capitalizing first letter

### Steps to reproduce 🕹

Steps to reproduce:

1. Add label in all lowercase letters
2. See the label

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by zettca** [comment]
Hello @aanjum154 👋 

I'm not completely sure I understood the issue here. Did you expect the text not to be capitalised? Because that's the component's expected behaviour.

(Since https://github.com/lumada-design/hv-uikit-react/pull/3469) `HvBreadcrumb` capitalises the text with just CSS, which you can easily change by overriding the `link` class:
```tsx
<HvBreadcrumb classes={{link: css({textTransform: "inherit"})}} ... />
```

Would this be enough for you, or did I not understand the issue correctly?

**Comment by aanjum154** [comment]
> Hello @aanjum154 👋
> 
> I'm not completely sure I understood the issue here. Did you expect the text not to be capitalised? Because that's the component's expected behaviour.
> 
> (Since #3469) `HvBreadcrumb` capitalises the text with just CSS, which you can easily change by overriding the `link` class:
> 
> ```tsx
> <HvBreadcrumb classes={{link: css({textTransform: "inherit"})}} ... />
> ```
> 
> Would this be enough for you, or did I not understand the issue correctly?

Yes I think this should fix it. Thanks
