### ISSUE TITLE
Use of `window` in the project makes UI Kit not compatible with Next.js

### ISSUE THREAD

**Issue by urkopineda** [lumada-design/hv-uikit-react#3501]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

We are upgrading our project that uses Next.js to UI Kit v5.x. Seems that the component `HvInput` is using the variable `window` unprotected, unaware if it's being called on client or server side. This is breaking our web app completely.

<img width="983" alt="Screenshot 2023-07-10 at 17 12 18" src="https://github.com/lumada-design/hv-uikit-react/assets/9933709/bb2ee8da-a4c2-4285-886d-60a8b486b86f">

### Expected behavior 🤔

We should be able to upgrade to UI Kit v5.x using Next.js.

### Steps to reproduce 🕹

Enter sandbox link: https://stackblitz.com/edit/stackblitz-starters-kldnpr?file=pages%2Findex.js

And/or the steps to reproduce:

1. Just run the project.

### Your Environment 🌎

Device: Laptop
OS: macOS
Browser: Edge
Version: Latest

**Comment by zettca** [comment]
Hey @urkopineda, thanks for opening this!
The StackBlitz sandbox helps a lot 👌 

This is definitely an issue in our side, recently introduced. We'll get a fix ASAP

**Comment by MEsteves22** [comment]
Hello @urkopineda 👋

This was fixed on [@hitachivantara/uikit-react-core@5.19.2](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.19.2). 

Thank you for opening this issue!
