### ISSUE TITLE
Vertical Navigation - Tree View mode - Arrow to expand/collapse a parent menu is not visible if menu entry has a long label and an icon associated

### ISSUE THREAD

**Issue by paulaclemente** [lumada-design/hv-uikit-react#3510]
### Which version of NEXT UI Kit are you opening this bug for?

None

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Having a menu entry with a long label that has an icon associated, the text is truncated but the arrow to expand/collapse the tree is not visible:

<img width="445" alt="Screenshot 2023-07-11 at 15 38 34" src="https://github.com/lumada-design/hv-uikit-react/assets/412752/a073e686-9224-4d26-b488-081ce8f718eb">

### Expected behavior 🤔

The arrow to expand/collapse the tree should be always displayed, regardless of the menu entry having a short/long label and having or not an icon associated.

### Steps to reproduce 🕹

And/or the steps to reproduce:

1. Open Storybook
2. Go to "Vertical Navigation -> Collapsible Icons" example, and expand the panel
3. Right-click on "Hardware" label (which contains an expand icon) and open the Web Inspector: change the label so it has a long text
4. Notice that after changing the label, the expand arrow is not visible anymore

**Comment by francisco-guilherme** [comment]
@paulaclemente: https://hv-eng.atlassian.net/browse/HVUIKIT-6797

**Comment by MEsteves22** [comment]
Hello 👋

Thank you for opening this issue. This was fixed on [5.22.1](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.22.1).
