### ISSUE TITLE
App Switcher widget adds invalid 'aria-describedby' attribute

### ISSUE THREAD

**Issue by loonatic** [lumada-design/hv-uikit-react#3538]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

On the App Switcher widget, if we add an app configuration without description, the <a> has a 'aria-describedby' attribute pointing to a non-existent id (id of the description icon if it was to be present).

### Expected behavior 🤔

'aria-describedby' attribute not being an id reference when description is not present.

### Steps to reproduce 🕹

Enter sandbox link: https://lumada-design.github.io/uikit/master/?path=/docs/widgets-app-switcher--main

And/or the steps to reproduce:

1. Inspect the "No Description App"
2. Check the <button> element having the wrong attribute value

### Context 🔦

The app shell team is tracking down accessibility errors:

https://hv-eng.atlassian.net/browse/TAP-9562

### Your Environment 🌎

Device: [laptop]
OS: [Windows10]
Browser [chrome]
Version [115.0.5790.99 (Official Build) (64-bit)]

**Comment by MEsteves22** [comment]
Hello 👋

Thank you for opening this issue. This was fixed on [5.22.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.22.0).
