### ISSUE TITLE
`HvWizard` header with `HvGrid` container

### ISSUE THREAD

**Issue by stephaniegaspar** [lumada-design/hv-uikit-react#3552]
### Which version of NEXT UI Kit are you opening this bug for?

None

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When a `HvWizard` is open, the header is out of the `HvWizardTitle` container.

![image](https://github.com/lumada-design/hv-uikit-react/assets/108751625/9c0a80fc-6da0-4702-8d8e-4669404f7e96)

### Steps to reproduce 🕹

Enter sandbox link: 

And/or the steps to reproduce:

1. Open storybook and go to Wizard section: https://lumada-design.github.io/uikit/master/?path=/docs/lab-wizard--main
2. Click on `Show Wizard` button

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by zettca** [comment]
Hey @stephaniegaspar, thanks for reporting this 👍 
 
Looks like this bug was introduced after https://github.com/lumada-design/hv-uikit-react/pull/3533, although the `HvGrid` usage in `HvWizard` looks a bit uncommon

We'll take a look 👍

**Comment by MEsteves22** [comment]
Hello 👋

Thank you for opening this issue. This was fixed on [5.4.27](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-lab%405.4.27).
