### ISSUE TITLE
Snackbar content pops out of the block if there is not enough space for text

### ISSUE THREAD

**Issue by Quernest** [lumada-design/hv-uikit-react#3553]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Snackbar content pops out of the block if there is not enough space for text

![Unknown](https://github.com/lumada-design/hv-uikit-react/assets/21086792/9e7e7ad9-7be2-4266-bac9-52f710f5fdc3)

### Expected behavior 🤔

Text that doesn't fit will be cut off.

### Steps to reproduce 🕹

-

### Context 🔦

-

### Your Environment 🌎

Device: Laptop
OS: macOS Sonoma Version 14.0 Beta 
Browser: Google Chrome
Version Version 115.0.5790.114 (Official Build) (arm64)

**Comment by Quernest** [comment]
> Hello @Quernest 👋
> 
> `HvSnackbar` doesn't handle wrapping. You can use [`HvOverflowTooltip`](https://lumada-design.github.io/uikit/master/?path=/docs/components-tooltip-overflow-tooltip--main) if you want the ellipsis + tooltip. We have a [Snackbar sample that uses it](https://lumada-design.github.io/uikit/master/?path=/docs/components-snackbar--variants).
> 
> ```tsx
> <HvSnackbar label={<HvOverflowTooltip data="Very long text goes here" />} />
> ```
> 
> Alternatively, you can remove the `maxHeight` of the snackbar, but we don't really recommend doing that.
> 
> What do you think?

Well, It looks like a solution, but on individual snackbars.
It's good to define it somehow globally because this is a notification for errors that are unknown what size of text can be.

I'm using the `useHvSnackbar` hook which means that I have to provide a custom label in each call, or write a hook wrapper like this:

```tsx
export default function useCustomHvSnackbar() {
  const { enqueueSnackbar: enqueueSnackbarBase } = useHvSnackbar()

  const enqueueSnackbar = useCallback(
    (message: React.ReactNode, options?: Record<string, any> | undefined) =>
      enqueueSnackbarBase(message, {
        ...options,
        snackbarContentProps: {
          label: <HvOverflowTooltip data={message}>{message}</HvOverflowTooltip>,
        },
      }),
    [enqueueSnackbarBase]
  )

  return enqueueSnackbar
}
```

By the way, this does not work and gives me the following result:
<img width="377" alt="Screenshot 2023-08-03 at 12 17 18" src="https://github.com/lumada-design/hv-uikit-react/assets/21086792/952704b4-9ece-41db-a951-46751c676627">

Are there any other options?

**Comment by zettca** [comment]
You also need to not let `messageText` overflow.

In the sample we also have this:
```ts
snackbarContentProps={{ classes: { messageText: css({ maxWidth: "250px" }) } }}
```

I think `overflow: "hidden"` would be more suitable, since you don't have to guess/assume the sizes
```ts
snackbarContentProps={{ classes: { messageText: css({ overflow: "hidden" }) } }}
```

It might make sense to add `overflow: "hidden"` to the component itself. Let me try it out 👀

**Comment by MEsteves22** [comment]
Hello 👋

Thank you for opening this issue! The component was reviewed on version [5.24.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.24.0) in order for the content to not overflow. Let use know if you need anything else.
