### ISSUE TITLE
HvTable don't have search options

### ISSUE THREAD

**Issue by vijayabhaskerPandiri** [lumada-design/hv-uikit-react#3672]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

HvTable don't have search options on table level and column level, please suggest if you are using any other library for this issue.

### Examples 🌈

https://codesandbox.io/s/admiring-wood-8rxinu?file=/src/components/DataTable.js this have global search.

**Comment by zettca** [comment]
We do support it.

The `HvTable*` components are pretty much just HTML elements with some styling - they have no logic and you should be able to do whatever. If you replace the table elements with the UI Kit equivalents (`tr`>`HvTableRow`, `td`>`HvTableCell`, etc.) you should keep the same behaviour, but with the UI Kit styles.

We offer an `useHvTable` hook (wrapper of `react-table`) that should be used to handle all the table logic (sort/filter/pagination/etc.). Similarly to the elements above, if you replace the `react-table` instances with the UI Kit variants, you should keep a similar behaviour, but with some extra features (eg. `useHvRowSelection` adds the checkboxes for you).

I did just that [in this sample](https://stackblitz.com/edit/github-e9pfya?file=src%2FDataTable.tsx) (replaced the elements and hooks with the UI Kit variants), and it seems to work the same.

Does this answer your question?
