### ISSUE TITLE
How to open calendar with date range in  HvDatePicker

### ISSUE THREAD

**Issue by vijayabhaskerPandiri** [lumada-design/hv-uikit-react#3677]
I'm using HvDatePicker to show the calendar with ranges but as per requirement we should open calendar default page loading.

2. I need to use useHvGroupBy for grouping in table, could you please share running example in react js not typescript.

**Comment by vijayabhaskerPandiri** [comment]
1. While loading page i need to display range -date Picker with open state with today date.
https://lumada-design.github.io/uikit/master/?path=/docs/components-date-picker--main
2. please provide me in React type script only, that will very helpful to me.

**Comment by zettca** [comment]
> 1. While loading page i need to display range -date Picker with open state with today date.
>    https://lumada-design.github.io/uikit/master/?path=/docs/components-date-picker--main
> 2. please provide me in React type script only, that will very helpful to me.

1. `HvDatePicker` currently doesn't support being opened by default. Opening `DatePicker` will move the focus to the Calendar panel, which is not ideal. As a workaround, you can open the `HvDatePicker` once it mount with a `.click()` on the header element. Regarding the initial value, you can use the `startValue` prop to configure the value.
2. You can [paste any code sample here](https://transform.tools/typescript-to-javascript), and it'll remove the TypeScript types for you.

**Comment by zettca** [comment]
We've added the `expanded`/`defaultExpanded` props allow this control. Expect the release tomorrow morning 🚀
