### ISSUE TITLE
Expandable list - https://designsystem.hitachivantara.com/6c705d900/p/0889aa-list/b/485d23

### ISSUE THREAD

**Issue by pixellos** [lumada-design/hv-uikit-react#3699]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

Control of  List - Expandable as specified in DS
![image](https://github.com/lumada-design/hv-uikit-react/assets/13859373/13ec9c64-5fca-407e-8235-6938257fad11)

### Examples 🌈

https://designsystem.hitachivantara.com/6c705d900/p/0889aa-list/b/485d23

### Motivation 🔦

I'm trying to present a list of tenants, with some data as a child.
I'd have actions both on parents and children.
I'd need to be able to disable checkbox visibility, as there is single selection needed for this case..

**Comment by francisco-guilherme** [comment]
Hi @pixellos,
Can you be more specific on your issue? It was hard for us to understand the scope of it.
Anyway, we have on our backlog a [story](https://hv-eng.atlassian.net/browse/HVUIKIT-6826) to work on the expandable list pattern and we hope to have it available on the upcoming sprints.

**Comment by pixellos** [comment]
Can You maybe suggest when the expandable list would be available in Ui-kit? As we just need that component - are You open for the contribution?
