### ISSUE TITLE
HvSlider uses styles in an unsupported Case

### ISSUE THREAD

**Issue by Quernest** [lumada-design/hv-uikit-react#3718]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

There are warning related to incorrect case in css objects (HvSlider)

<img width="1181" alt="Screenshot 2023-09-29 at 17 43 29" src="https://github.com/lumada-design/hv-uikit-react/assets/21086792/a8786dd4-6be5-458a-9a7f-2a4b6745b1a6">

### Expected behavior 🤔

There shouldn't be this warning

**Comment by zettca** [comment]
Hello @Quernest. Thanks for reporting this 👍

**Comment by MEsteves22** [comment]
Hello @Quernest, I fix for this is available on [@hitachivantara/uikit-react-core@5.28.1](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.28.1). Thanks for reporting this issue 🙏
