### ISSUE TITLE
Plotly Dash component implementation

### ISSUE THREAD

**Issue by yifei-hitachi** [lumada-design/hv-uikit-react#3734]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

Hi I really like the design of the UI.
I'm wondering do your team have plans to building a dash-component version of the Hitachi UI react Library. 
We are currently prototyping with Python dash app, and not too many people good with writing JS or react. 
If we can have dash-component of this UI , that would be fantastic. 

Thanks for reading. 
Sincerely

### Examples 🌈

some dash component examples : 
https://dash-bootstrap-components.opensource.faculty.ai/
https://www.dash-mantine-components.com/

**Comment by francisco-guilherme** [comment]
Hi @yifei-hitachi, thanks for your feedback.
Unfortunately we are not planning on support your use case.
If you have any ideia on how to materialise it please let us know.
