### ISSUE TITLE
Disable Apply button if no values are selected from the dropdown option in the HvDropdown.

### ISSUE THREAD

**Issue by sahillihas2021** [lumada-design/hv-uikit-react#3763]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

<HvDropdown
					aria-label="Right"
					disablePortal
					id="dropdown"
					multiSelect
					showSearch
					onChange={}
					--- onApply={} //It should disable the Apply Button ---
					values={}
				/>
				
Based upon this: https://lumada-design.github.io/uikit/master/?path=/docs/components-dropdown--docs

### Examples 🌈

Apply button should not be clickable.
![image](https://github.com/lumada-design/hv-uikit-react/assets/93397536/d8e31e13-03b0-47a5-9a95-341522cdc8d5)

### Motivation 🔦

When no values are selected from the dropdown options in the HvDropdown then the Apply) button should be disabled and when 1 value is selected (As soon as) then the apply button should be enabled.

**Comment by MEsteves22** [comment]
Hello @sahillihas2021 👋 This improvement is available on [@hitachivantara/uikit-react-core@5.35.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.35.0). Thank you 🙏

**Comment by sahillihas2021** [comment]
Hi 
But the requirement was when 0 values are selected from the HvDropDown it should disable the Apply Button & as soon as 1 value is selected it should enable the apply button.
 
There is no requirement of checking for the (no changes to apply on the initial state). It should be if No. of checkboxes clicked > 0 then enable apply button else disable the apply button.

**Comment by sahillihas2021** [comment]
![MicrosoftTeams-image (28)](https://github.com/lumada-design/hv-uikit-react/assets/93397536/1c4435e1-bad8-4fb0-be7f-525852c5e3fd)
In my current project requirement - 1 Value will be by-default selected on the initial page load. For that it's disabling the Apply Button.
