### ISSUE TITLE
Flow - dropdow menu should ajust when zoom in or zoom out 

### ISSUE THREAD

**Issue by hv-carlamartins** [lumada-design/hv-uikit-react#3766]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When we open the dropdown and we zoom in or zoom out the menu not adjust

![image](https://github.com/lumada-design/hv-uikit-react/assets/42973059/c26633dd-9049-480b-a194-6f55694dc28b)

### Expected behavior 🤔

The menu should adjust when we zoom in or zoom out

### Steps to reproduce 🕹

Enter sandbox link: https://lumada-design.github.io/uikit/master/?path=/docs/lab-flow--docs

And/or the steps to reproduce:

1. Drag Dashboard to canvas
2. Zoom in 
3. Open the dropdown menu

**Comment by plagoa** [comment]
hey @hv-carlamartins, thanks for the issue. this has been addressed in [this PR](https://github.com/lumada-design/hv-uikit-react/pull/3768) and will be available in the next release.

**Comment by MEsteves22** [comment]
Hello @hv-carlamartins, the fix for this problem is available on [@hitachivantara/uikit-react-lab@5.12.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-lab%405.12.0). Thanks for opening this issue 🙏
