### ISSUE TITLE
Dropdown component breaks server-side rendering

### ISSUE THREAD

**Issue by adafia** [lumada-design/hv-uikit-react#3774]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Server rendering the `HvDropdown` component produces a Server Error with the reference "document is not defined". 

### Expected behavior 🤔

The `HvDropdown` component should lend itself to server-side rendering.

### Steps to reproduce 🕹

Enter sandbox link: 

1. [sandbox with the bug](https://codesandbox.io/p/github/adafia/hitachi-vantara-dropdown/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo70f8t300073b6jcsn9hqc5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo70f8t300033b6jdbgnzuye%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo70f8t300053b6jgkn2gk4v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo70f8t300063b6jbg6e2iv1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.92926528583692%252C51.07073471416308%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo70f8t300033b6jdbgnzuye%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo70f8t300023b6jobojy9a4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clo70f8t300033b6jdbgnzuye%2522%252C%2522activeTabId%2522%253A%2522clo70f8t300023b6jobojy9a4%2522%257D%252C%2522clo70f8t300063b6jbg6e2iv1%2522%253A%257B%2522id%2522%253A%2522clo70f8t300063b6jbg6e2iv1%2522%252C%2522activeTabId%2522%253A%2522clo70gkv800d13b6ji54r5e2v%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clo70f8wp000p3b6jpqp833sq%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clo70gkv800d13b6ji54r5e2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clo70f8t300053b6jgkn2gk4v%2522%253A%257B%2522id%2522%253A%2522clo70f8t300053b6jgkn2gk4v%2522%252C%2522activeTabId%2522%253A%2522clo70f8t300043b6jvw4wfgtb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo70f8t300043b6jvw4wfgtb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo70f927000negjs97o56h8w%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clo70fakp007x3b6jemudo7ke%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

2. [sandbox with workaround](https://codesandbox.io/p/github/adafia/test-hitachi-vantara/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clo2wi35p00073b6jcp5nhazm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clo2wi35p00033b6ja4nugabh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clo2wi35p00053b6j6y2tprc5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clo2wi35p00063b6jbu50i206%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clo2wi35p00033b6ja4nugabh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo2wi35p00023b6jiun8t1p1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clo2wi35p00033b6ja4nugabh%2522%252C%2522activeTabId%2522%253A%2522clo2wi35p00023b6jiun8t1p1%2522%257D%252C%2522clo2wi35p00063b6jbu50i206%2522%253A%257B%2522id%2522%253A%2522clo2wi35p00063b6jbu50i206%2522%252C%2522activeTabId%2522%253A%2522clo2x4en300q63b6jqcv3t3zs%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clo2wi39d000p3b6j0hqvltk5%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clo2wkbua00f13b6jt8bcd8ye%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdropdown%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522id%2522%253A%2522clo2x4en300q63b6jqcv3t3zs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clo2wi35p00053b6j6y2tprc5%2522%253A%257B%2522id%2522%253A%2522clo2wi35p00053b6j6y2tprc5%2522%252C%2522activeTabId%2522%253A%2522clo2wi4aa008f3b6jixoywq5x%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clo2wi35p00043b6j6echsmai%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clo2wi3i7000qeek30ghvajq8%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clo2wi4aa008f3b6jixoywq5x%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

And/or the steps to reproduce:
1. Start a new Next.js v13.x application with `npx create-next-app@latest hitachi-vantara-dropdown`
2. Setup the HV Next UI kit following the [manual setup instructions](https://lumada-design.github.io/uikit/master/?path=/docs/overview-get-started--docs). This includes wrapping the app in the `HvProvider` from "@hitachivantara/uikit-react-core".
3. Without disabling SSR, Import and use `HvDropDown` from "@hitachivantara/uikit-react-core" and use it.
4. run "npm run dev"

#### Environment and Dependencies

We use the Hitachi Next UI kit in a server-side rendered Next.js v13 application. Here are the relevant dependencies:
```
  "@emotion/react": "11.11.1",
  "@emotion/styled": "11.11.0",
  "@hitachivantara/uikit-react-core": "5.32.0",
  "@mui/material": "5.14.14",
  "next": "13.5.6",
  "react": "18",
  "react-dom": "18"
```

#### Pain points

Anytime we use the `HvDropdown` component from "@hitachivantara/uikit-react-core", we have to disable SSR to prevent it from breaking. This prevents us from fully reaping the benefits of SSR.

#### Possible cause of the bug and solution

Reference to **document** is made several times in [BaseDropDown](https://github.com/lumada-design/hv-uikit-react/blob/c3dfa0e28fb43a89c410cd673b7e3ab20a7b70c6/packages/core/src/components/BaseDropdown/BaseDropdown.tsx#L438C9-L438C9) and "document" is only defined in the client environment (i.e. browser) and not in the server environment.

An environment check could be done before using browser-specific code.

### Your Environment 🌎

Device: Laptop
OS: macOS 14.0
Browser: Chrome

**Comment by francisco-guilherme** [comment]
Hi @adafia, tks for your feedback.
We are aware of these issues, but for now they haven't been prioritised since you can use dynamic import in order to unblock the component usage.
Let me know if you need more info on this.
