### ISSUE TITLE
Dropdown menu icon aligment 

### ISSUE THREAD

**Issue by fookoo** [lumada-design/hv-uikit-react#3780]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

i got code like so:

```
<HvDropDownMenu
        autoFocus={false}
        category="secondarySubtle"
        icon={<PersonIcon />}
        dataList={[
          {
            id: 'logout-action',
            icon: <LogoutIcon fontSize="small" />,
            label: 'Logout'
          }
        ]}
        expanded={isOpen}
        placement="left"
        onClick={handleDropdownSelect}
        onToggle={toggle}
      />
 ```

LogoutIcon come from @mui/icons

and its look like so
![image](https://github.com/lumada-design/hv-uikit-react/assets/7860124/89e272a1-020b-476d-a188-26ce82fb4e1e)

### Expected behavior 🤔

according to docs:

![image](https://github.com/lumada-design/hv-uikit-react/assets/7860124/e909c8e5-477f-4e9e-acf4-617e4ee4bb35)

### Your Environment 🌎

Device: Laptop
OS: Windows 10
Browser Latest Chrome
Version Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by zettca** [comment]
Hey @fookoo 👋 

`HvDropdownMenu` is expecting a UI Kit icon, which has a `32x32` container. You should add a container to the MUI icon, or use one of the icons in the UI Kit library (ie. `Login` or `Logout`)
