### ISSUE TITLE
`HvTableCell` sorted color not showing on first render

### ISSUE THREAD

**Issue by stephaniegaspar** [lumada-design/hv-uikit-react#3804]
### Which version of NEXT UI Kit are you opening this bug for?

None

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Some of table cells don't render css property `background-color` on first render. When some rows are rendered after others, the css property is only set with the right color after the mount of the `HvTableCell` component located on the current sort column.

### Expected behavior 🤔

The css property `background-color` must be set before showing cells that are part of the current sorted column.

### Steps to reproduce 🕹

Enter sandbox link: 

And/or the steps to reproduce:

https://github.com/lumada-design/hv-uikit-react/assets/108751625/a6d4bbbc-fd0e-4767-8973-5176e7c30f2a

### Context 🔦

This issue is not a high priority for the affected project.

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by MEsteves22** [comment]
Hello @stephaniegaspar 👋

Thanks for opening this issue, we'll look into it!

**Comment by MEsteves22** [comment]
Hello 👋

This was fixed on [@hitachivantara/uikit-react-core@5.36.5](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.36.5). Thanks!
