### ISSUE TITLE
`HvOverflowTooltip` paragraph mode doesn't work

### ISSUE THREAD

**Issue by stephaniegaspar** [lumada-design/hv-uikit-react#3810]
### Which version of NEXT UI Kit are you opening this bug for?

None

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When `HvOverflowTooltip` is rendered with property `paragraphOverflow: true`, the text won't truncate with ellipsis when overflows a parent component.

### Expected behavior 🤔

The property should take effect on every scenario when a text is expected to be presented with 2 or more lines and be truncated when overflows a parent component. A `Tooltip` should also be shown.

### Steps to reproduce 🕹

Enter sandbox link: 

And/or the steps to reproduce:

![image](https://github.com/lumada-design/hv-uikit-react/assets/108751625/ef613891-1bd0-457d-9793-974fde7e2924)
![image](https://github.com/lumada-design/hv-uikit-react/assets/108751625/2c5e40aa-fe09-4c37-a4cc-e6c4e35656e9)

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....]
Browser [e.g. stock browser, safari, chrome]
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by stephaniegaspar** [comment]
Related work [MLAAS-2895](https://hv-eng.atlassian.net/browse/MLAAS-2895).

**Comment by zettca** [comment]
Thanks for reporting this @stephaniegaspar 🙏 
We'll look into it
