### ISSUE TITLE
HvQueryBuilder should allow dropdowns in value field

### ISSUE THREAD

**Issue by vkumarakella** [lumada-design/hv-uikit-react#3834]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

In the Query builder,

once user selects an **attribute** of type **dateandtime**
-- There should be **three operators** included **"is older than", "is younger than" and "range"**.
-- On selecting **"is older than" or "is younger than"** -- it should display **two** dropdowns in the value place
-- the first is with the value options **0 to 12**
-- the second is with the value options **"Seconds, Minutes, Hours, Days, Months, Years, Weeks, Fortnights, Quarters"**

-- On selecting, the operator **range**, it should show two instances of the dropdowns
     -- first dropdown  second dropdown
     -- first dropdown  second dropdown
 

### Examples 🌈

As a example,
once user selects an **attribute** of type **dateandtime**
-- There should be **three operators** included **"is older than", "is younger than", "range"**.
-- On selecting **"is older than" or "is younger than"** -- it should display **two** dropdowns in the value place
-- the first is with the value options **0 to 12**
-- the second is with the value options **"Seconds, Minutes, Hours, Days, Months, Years, Weeks, Fortnights, Quarters"**

The query json would look like

{
  "combinator": "or",
  "rules": [
    {
      "attribute": "lastScannedDate",
      "operator": "isOlderThan",
      "value": "3 Months"
    },
     {
      "attribute": "lastScannedDate",
      "operator": "isYoungerThan",
      "value": "3 Years"
    }
  ]
}

-- On selecting, the operator **range**, it should show two instances of the dropdowns
     -- first dropdown  second dropdown
     -- first dropdown  second dropdown
     
The query json would look like

{
  "combinator": "and",
  "rules": [
    {
      "attribute": "lastScannedDate",
      "operator": "range",
      "value": {
        "start": "3 Months",
        "end":  "3 Years"
      }
    }
  ]
}

![image](https://github.com/lumada-design/hv-uikit-react/assets/129264654/5e5880f5-aa55-478a-8c5a-3902208b6322)

[https://hv-eng.atlassian.net/browse/PO-661]([https://hv-eng.atlassian.net/browse/PO-661](https://github.com/lumada-design/hv-uikit-react/issues/url))

**Comment by MEsteves22** [comment]
Hello @vkumarakella 👋

In the latest UI Kit version ([@hitachivantara/uikit-react-core@5.37.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.37.0)) it's now possible to add custom value renderers to the query builder. With this new feature, you'll be able to implement the use case described in this issue. Previously any custom attribute type was rendering a text input. You can now provide custom renderers through the `renderers` prop.

Please, take a look at [this sample](https://lumada-design.github.io/uikit/master/?path=/docs/widgets-query-builder--docs#custom-renderers) to know how to achieve this. The sample's source code can be found [here](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/components/QueryBuilder/stories/CustomRenderers.tsx). 

It's also possible to disable the confirmation dialogs when removing rules and rule groups. If this is something you need, use the `disableConfirmation` prop.

Thank you!
