### ISSUE TITLE
HvFileUploader acceptedFiles prop

### ISSUE THREAD

**Issue by fookoo** [lumada-design/hv-uikit-react#3852]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

According to [documentation](https://lumada-design.github.io/uikit/master/?path=/docs/widgets-file-uploader--docs)

acceptedFiles is suppose to describe what file extensions are acceptable.

so i assume that code:

```
        <HvFileIploader
          fileList={fileList}
          maxFileSize={MAX_FILE_UPLOAD_SIZE}
          acceptedFiles={['scd']}
          onFilesAdded={(files) => {
            setFileList(files)
            console.log(files.at(0)?.type)
          }}
        />
```

allows me to upload any *.scd file

but it gives me type error when i tried to upload scd file

`console.log(files.at(0)?.type)`
 gives me empty string
 
 
![image](https://github.com/lumada-design/hv-uikit-react/assets/7860124/8544749d-1152-40c5-9d87-5148c571c5ef)

### Expected behavior 🤔

to be able to specify extension 

### Your Environment 🌎

Device: Desktop
OS: Windows 11
Browser: Chrome
Version 5.36.1

**Comment by MEsteves22** [comment]
Hello @fookoo 👋

In this case you'll have to use `acceptedFiles={[".scd"]}` (the dot is missing).

**Comment by smietanka** [comment]
Hello @MEsteves22 
Unfortunetly I had the same problem. I used `.scd` file extension as you mentioned. 
Using this solution (with dot) I started to see 
![image](https://github.com/lumada-design/hv-uikit-react/assets/17428659/1a1e553b-2fd0-4d02-b144-c1610d4f96ae)
and selected by default `scd` extension inside of default browser file uploader. Unfortunetly error still occures. Even this I am still able to upload file with different extension
![image](https://github.com/lumada-design/hv-uikit-react/assets/17428659/bde6a10c-f10c-4ece-8209-f529e529acca)

**Comment by MEsteves22** [comment]
Hello 👋

Can you let us know if you are able to upload an `scd` file using [this example](https://stackblitz.com/edit/github-ixonro-zenoa5?file=src%2FApp.tsx,src%2Fmain.tsx), please? On my hand it seems to be working:

https://github.com/lumada-design/hv-uikit-react/assets/43220251/56de5b27-e5ae-4796-a08f-b35d72eab731

If not, can you try to reproduce the error on Stackblitz and send us the link? 🙏
