### ISSUE TITLE
Add possibility to add Tags in TagsInput outside of ones given in Suggestions list.

### ISSUE THREAD

**Issue by stabor705** [lumada-design/hv-uikit-react#3877]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

Currently, when `suggestionListCallback` is set, only Tags selected from Suggestion list can be added in TagsInput. It would be helpful if there was an option to make Suggestions only optional and user could still add new Tags by hitting enter. With this should also come a way to provide custom callback for validating new Tag.

### Motivation 🔦

At Hitachi Energy, we use TagsInput as a component that allows to assign Tags that already exist in the system, as well as create completely new tags. This is done by setting `suggestionListCallback` and there, prepending to a list of matching tags a "+ Add {text input value}" entry. This works reasonably well, but is unintuitive, because adding new Tag requires either clicking on "+ Add..." entry, or navigating to it using arrow keys, whereas user will probably try to do it immediately by hitting enter.

**Comment by plagoa** [comment]
Hey @stabor705, this seems to make sense. We'll work on it.

**Comment by MEsteves22** [comment]
Hello @stabor705 👋

This feature was added in [@hitachivantara/uikit-react-core@5.39.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.39.0). You'll have to set `suggestionsLoose` to `true` and use `suggestionValidation` to validate the tags. You can find an example [here](https://github.com/lumada-design/hv-uikit-react/blob/master/packages/core/src/components/TagsInput/TagsInput.stories.tsx#L456). Thanks 🙏
