### ISSUE TITLE
HvDropDownMenu component does not allow to show the selected value

### ISSUE THREAD

**Issue by Quernest** [lumada-design/hv-uikit-react#3919]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

I have no way to show the selected value because

https://github.com/lumada-design/hv-uikit-react/blob/5d2df079c4d3e8b19badd85be4e98b4d778e6d84/packages/core/src/DropDownMenu/DropDownMenu.tsx#L169

### Expected behavior 🤔

Provide `ListProps` to overwrite default values or remove `selectable={false}` prop

**Comment by zettca** [comment]
Hey @Quernest 👋 

`HvDropdownMenu` currently doesn't support selection, as its purpose is to display actions.

`HvDropdown` supports selection and a bunch of other things, isn't this component a suitable alternative? If not, can you share your use case with us?

**Comment by zettca** [comment]
Hey @Quernest

Using a `HvDropdownMenu`-like menu for that use-case makes it hard for the user to understand the filters being applied.
But if really needs to be a menu like that, you can use the `HvDropdown` and change a couple of styles to make it look the the `HvDropdownMenu`.

Here's a Stackblitz with a couple of samples: https://stackblitz.com/edit/github-ougzhl?file=src%2FApp.tsx

I'm marking this as resolved. Let me know if you face any issues

**Comment by Quernest** [comment]
> Hey @Quernest
> 
> Using a `HvDropdownMenu`-like menu for that use-case makes it hard for the user to understand the filters being applied. But if really needs to be a menu like that, you can use the `HvDropdown` and change a couple of styles to make it look the the `HvDropdownMenu`.
> 
> Here's a Stackblitz with a couple of samples: https://stackblitz.com/edit/github-ougzhl?file=src%2FApp.tsx
> 
> I'm marking this as resolved. Let me know if you face any issues

Hey @zettca 
Is it possible dynamically replace Dropdown's `Down` icon based on selected value?
This way filter operation will be associated with specific icon.

**Comment by zettca** [comment]
> Hey @zettca Is it possible dynamically replace Dropdown's `Down` icon based on selected value? This way filter operation will be associated with specific icon.

Yes - for example, you can configure the `HvBaseDropdown` to:
- remove/hide the default icon (`classes.arrowContainer`)
- configure the `placeholder` to be something else

I've added [another sample to the Stackblitz](https://stackblitz.com/edit/github-ougzhl?file=src%2FApp.tsx%3AL49)

**Comment by Quernest** [comment]
> > Hey @zettca Is it possible dynamically replace Dropdown's `Down` icon based on selected value? This way filter operation will be associated with specific icon.
> 
> Yes - for example, you can configure the `HvBaseDropdown` to:
> 
> * remove/hide the default icon (`classes.arrowContainer`)
> * configure the `placeholder` to be something else
> 
> I've added [another sample to the Stackblitz](https://stackblitz.com/edit/github-ougzhl?file=src%2FApp.tsx%3AL49)

Thank you
