### ISSUE TITLE
HvTable - issues with resizing, sorting, and sticky behaviour

### ISSUE THREAD

**Issue by Quernest** [lumada-design/hv-uikit-react#3933]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

**Bug 1: Conflict between resizing and sticky columns functionality**

When using the `useHvResizeColumns` hook along with `useHvTableSticky`, there is a conflict in UI behavior. Specifically, applying `useHvResizeColumns` causes the column header to lose its sticky property (its position 'relative'), leading to the header horizontal scrolling along with the content, as demonstrated in the attached video.

**Bug 2: Transparency Issue after sorting**

After applying the `useHvSortBy` hook and performing a sorting operation, the column background becomes transparent, allowing values from other columns to be visible underneath the sticky column.

**Bug 3: Sorting function calls after resize**

While resizing columns there is a continuous invocation of the sorting function. This occurs after the resize process leading to unnecessary sorting calls.

### Expected behavior 🤔

**Bug 1**
Column (including header) should remain sticky while using both `useHvResizeColumns` and `useHvTableSticky`.

**Bug 2**
The background should remain opaque after sorting, preventing values from other columns from being visible.

**Bug 3**
The sorting function should only be called when a sorting operation is explicitly triggered, not after column resizing.

### Steps to reproduce 🕹

You can use [Complete Table](https://lumada-design.github.io/uikit/master/?path=/docs/visualizations-table-complete-table--docs) as an example.

**Bug 1**

1. Apply useHvResizeColumns hook to the table.
2. Enable useHvTableSticky hook for the sticky behavior.
3. Observe the header behavior during horizontal scrolling.

**Bug 2**

1. Apply `useHvSortBy` and `useHvTableSticky` hooks to enable sorting functionality.
2. Scroll horizontally a bit and perform a sorting operation on the sticky column.
3. Observe the transparency issue in the sticky column.

**Bug 3**

1. Apply `useHvSortBy` and `useHvResizeColumns` hooks to enable column sorting and resizing.
2. Resize any column, and observe the sorting function being called

https://github.com/lumada-design/hv-uikit-react/assets/21086792/b4c8db00-b738-4092-bb4f-c98b3d5a1f22

**Comment by MEsteves22** [comment]
Hello @Quernest 👋

Thank you for raising these issues. We'll be looking into them and let you know when fixes are available.

**Comment by MEsteves22** [comment]
Hello @Quernest 👋

All of these bugs should be fixed on [@hitachivantara/uikit-react-core@5.44.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.44.0). Thanks!
