### ISSUE TITLE
Split Button Feature request

### ISSUE THREAD

**Issue by wojciechpajor** [lumada-design/hv-uikit-react#3957]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

Hi I would like to let you know that it would be very helpful to have split button in hv-uikit

### Examples 🌈

https://designsystem.hitachivantara.com/6c705d900/v/39412/p/73880a-button/b/846069

### Motivation 🔦

Having supported split button would help to create clean and robust UI

**Comment by zettca** [comment]
Hello @wojciechpajor 👋 

Thanks for bringing this up - we'll be adding this to our backlog. 👍 
We'll let you know once it's released

**Comment by zettca** [comment]
We just got a Split Button example merged.
Please let us know if you have any issues with it
