### ISSUE TITLE
Missing info on icon usage in docs

### ISSUE THREAD

**Issue by VitaliiSemchyshyn** [lumada-design/hv-uikit-react#3970]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

"Icons" section of docs https://lumada-design.github.io/uikit/master/?path=/docs/foundation-icons-library--docs misses information.
I wasn't able to understand these things:
1. How to install icons package.
2. How to import icon component from package.
3. What "spriteUrl" input means and what value I should use.
4. In "Usage" sub-section there is code example using `<p>` tag, I don't understand how it becomes icon.

### Expected behavior 🤔

I expect to see understandable spep-by-step guide on how to install icons package and use it in my project.

**Comment by MEsteves22** [comment]
Hello @VitaliiSemchyshyn 👋

Sorry for the missing information on our docs, we'll update them. Thanks for raising this 🙏 

In the meantime, I'll answer some of your questions here:
1. You can install the icons package with `npm i @hitachivantara/uikit-react-icons`
2. You can import an icon by doing `import { Edit } from "@hitachivantara/uikit-react-icons"` and then use the icon by doing `<Edit />`
3. `spriteUrl` can be used when you use the `HvIconSprite` component imported through `import { HvIconSprite } from "@hitachivantara/uikit-react-icons"`. This property is the location of the icon sprite file, i.e. the `svg` file containing all the icons you can choose from. In our `@hitachivantara/uikit-react-icons` build, you can find the icon sprite files inside `dist/sprites`. You'll need to copy these files to your app and then provide the path to `spriteUrl`.
4. We are currently having some problems with the code generated in some of our samples, and it's the case with this one. This shouldn't be a `p` tag but `CheckboxCheck` imported with `import { CheckboxCheck } from "@hitachivantara/uikit-react-icons"`.

**Comment by VitaliiSemchyshyn** [comment]
@MEsteves22 Thanks for answer!

**Comment by MEsteves22** [comment]
Hello 👋

We updated the [icons section](https://lumada-design.github.io/uikit/master/?path=/docs/foundation-icons--docs) in docs. Once again, thanks for opening this issue!
