### ISSUE TITLE
Unable to clear HvTimePicker value and return it to undefined state 

### ISSUE THREAD

**Issue by guilherme-jsv-soares** [lumada-design/hv-uikit-react#3971]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When the control is set with a value it's not possible to clear/reset it to an undefined/null state (and return the UI to show the placeholder, for example).

### Expected behavior 🤔

It should be possible to reset the HvTimePicker value to undefined/null.

### Steps to reproduce 🕹

Enter sandbox link: 

And/or the steps to reproduce:

1.
2.
3.
4.

**Comment by zettca** [comment]
Hey @guilherme-jsv-soares, thanks for reporting this 🙏 

`value={undefined}` should always mean that the component is uncontrolled in our components.
To represent and "empty" and controlled value, `null` should be passed; but there's a bug not allowing it - we'll work on fixing this

**Comment by MEsteves22** [comment]
Hello @guilherme-jsv-soares 👋

This bus was fixed on [@hitachivantara/uikit-react-core@5.44.5](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.44.5). Thanks for opening this issue!

**Comment by guilherme-jsv-soares** [comment]
Thank you everyone. Great work.
