### ISSUE TITLE
Pane to allow user to rearrange the columns order by dragging each column and placing either higher up or down.

### ISSUE THREAD

**Issue by ferm12** [lumada-design/hv-uikit-react#3977]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

A pane that allows users to select which columns they wish to see on the table and in what order. If a checkbox is selected, that column is showing in the table. If a checkbox is not selected  that columns is hidden/not showing in the table. User can also rearrange the columns order by dragging(drag & drop) each column and placing either higher up or down. The order of columns should reflect in the order of the columns in the table. 

### Examples 🌈

In this screenshot,  there are 2 sections, the Fixed section and the Dynamic. In the Fixed section the user should not be able to drag & drop the columns because they are Fixed. However, in the Dynamic section, the user should be able to drag & drop (rearrange) columns. 
![ui-kit-table-column-dragndrop](https://github.com/lumada-design/hv-uikit-react/assets/3270602/732edad4-211f-47f2-8d44-e96ad40ad98c)

### Motivation 🔦

This new feature comes from redesigning entire UI App using the HV UI Kit.

**Comment by zettca** [comment]
Hey @ferm12 👋 

Currently, the UI Kit has no built-in Drag & Drop handing, nor is it in our short-term roadmap.
But this shouldn't be a blocker for you. You should be able to easily integrate our components with any Drag & Drop library of your choosing.
Here's a quick example: https://stackblitz.com/edit/github-zuhsjd?file=src%2FApp.tsx

Regarding the integration with the table's `columns` order, if should be managed by your application

**Comment by MEsteves22** [comment]
Hello @ferm12 👋

We now have a working example [here](https://lumada-design.github.io/uikit/master/?path=/docs/visualizations-table-table-section--docs) in our documentation under "Table Settings".

I'll be closing this issue. If you need anything else let us know, thanks!
