### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by xcalculus** [lumada-design/hv-uikit-react#4011]
### Which version of NEXT UI Kit are you opening this bug for?

None

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Compiled with problems:
×
ERROR in ./src/components/Entities/Attributelist/Attributelist.js 8:0-86
Module not found: Error: Package path ./dist is not exported from package D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core (see exports field in D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core\package.json)

ERROR in ./src/components/Entities/EntityList/EntityList.js 6:0-100
Module not found: Error: Package path ./dist is not exported from package D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core (see exports field in D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core\package.json)
ERROR in ./src/components/Search/Attributelist/Attributelist.js 8:0-100
Module not found: Error: Package path ./dist is not exported from package D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core (see exports field in D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core\package.json)
ERROR in ./src/components/Sources/SourceEntities/SourceEntities.js 8:0-86
Module not found: Error: Package path ./dist is not exported from package D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core (see exports field in D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core\package.json)
ERROR in ./src/components/Sources/SourceList/SourceList.js 6:0-100
Module not found: Error: Package path ./dist is not exported from package D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core (see exports field in D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core\package.json)
ERROR in ./src/views/Login/Login.js 7:0-85
Module not found: Error: Package path ./dist is not exported from package D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core (see exports field in D:\Projects\dpm-ui\node_modules\@hv\uikit-react-core\package.json)

### Expected behavior 🤔

Application must compile without errors

### Steps to reproduce 🕹

Enter sandbox link: 

And/or the steps to reproduce:

1.
2.
3.
4.

### Context 🔦

Unable to launch the application locally

### Your Environment 🌎

Device: [e.g. Laptop, Mobile, ....] Laptop AWS workspace
OS: [e.g. iOS8.1] Windows
Browser [e.g. stock browser, safari, chrome] Chrome
Other details [e.g. screen resolution 1920x1080, ...]

**Comment by zettca** [comment]
Hey @xcalculus 👋 

This looks related to your build configuration or how you're importing UI Kit. Can you tell us a bit more about your envirnoment? Specifically:
- What UI Kit version are you using? And how are you importing the components? (keep in mind that only v3 or later are supported)
-  Which tools are your using to build the project? Can you share the build configuration?

**Comment by xcalculus** [comment]
We are using 2.22.0 version. However, when I tried to upgrade, I am getting errors.

**Comment by xcalculus** [comment]
Hi, thanks for reaching out. Meeting would be great. What time can we schedule?
Milind

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by xcalculus** [comment]
I was able to get it to work by downgrading Node JS to 16.16.0 version from 20.11.1. I am using @hv/uikit-react-core version 2.22.0
However, I would like to HV-UI-KIT to work with Node 20.11.1
