### ISSUE TITLE
Console error being thrown when a disabled button is passed into a Tooltip

### ISSUE THREAD

**Issue by guilherme-jsv-soares** [lumada-design/hv-uikit-react#4013]
### Which version of NEXT UI Kit are you opening this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

The IconButton component in the HvPagination component is throwing an error because of passing a disabled button into a tooltip.
![image](https://github.com/lumada-design/hv-uikit-react/assets/35031275/06221e69-2b21-4be2-b113-5b85ba9d753d)

### Expected behavior 🤔

Shouldn't throw any error

### Steps to reproduce 🕹

1. Add a pagination component
2. Disable the pagination forward and backward buttons through the `canPrevious` or `canNext` props.

**Comment by zettca** [comment]
Hey @guilherme-jsv-soares 👋 

Thanks for raising this issue. This is already being addressed in this PR: https://github.com/lumada-design/hv-uikit-react/pull/4005

**Comment by MEsteves22** [comment]
Hello @guilherme-jsv-soares 👋

You can expected the fix for this issue in our next release. Thanks 🙏
