### ISSUE TITLE
Typescript errors after upgrading react to latest version

### ISSUE THREAD

**Issue by sachinlandage88** [lumada-design/hv-uikit-react#4043]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Currently, we are using React 17.0.2, and everything working fine. 
Recently we decided to upgrade the react version i.e. 18.2.0 and after that entire application broke because of a typescript error. 
![image](https://github.com/lumada-design/hv-uikit-react/assets/123560009/ccdbb49d-41b5-4dae-8036-d7e090670355)

Here is a list of packages which I upgraded along with react. 
"@hitachivantara/uikit-react-core": "^5.50.1",
"@hitachivantara/uikit-react-icons": "^5.8.3",
"i18next": "^23.9.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-router-dom": "^6.22.1",
"@types/react": "^18.2.57",
"@types/react-dom": "^18.2.19",
"typescript": "^4.3.4"

Thank you!

### Expected behavior 🤔

UIKIT packages should work with React's latest version. 

### Steps to reproduce 🕹

Sandbox link: 

Steps to reproduce:

1.
2.
3.
4.

### Your Environment 🌎

Build tool: (e.g. Vite 4, Webpack 5)
Device & OS: (e.g. Windows 11 laptop, iPhone 13 iOS15)
Browser: (e.g. Chrome 112, Safari 15.4)
Other details (e.g. 4K resolution, ...)

**Comment by zettca** [comment]
Thanks for reporting this @sachinlandage88, we'll look into this 👍

**Comment by sachinlandage88** [comment]
Hi @MEsteves22 we will make changes according to this and will let you know if need more help on this. 

Thank you!
Sachin

**Comment by sachinlandage88** [comment]
Hello @MEsteves22 suggested fix working for me. Please feel free to close this ticket. 

Thank you,
Sachin

**Comment by zettca** [comment]
Thanks for the update 👍
