### ISSUE TITLE
Add support for Maps component in hvuikit library

### ISSUE THREAD

**Issue by aanjum154** [lumada-design/hv-uikit-react#4049]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

**Comment by HQFOX** [comment]
Hi @aanjum154, 
We don't have any plans to add it right now, we do have a sample of an implementation using`leaflet` and `react-leaflet` you can see it [here](https://lumada-design.github.io/uikit/master/?path=/docs/templates-dashboard--docs)

**Comment by zettca** [comment]
Please let us know if the shared example based on leaflet isn't enough to suit your use-case @aanjum154
