### ISSUE TITLE
VerticalNavigation `disabled: true` does not disable `href`

### ISSUE THREAD

**Issue by MarkJBenson** [lumada-design/hv-uikit-react#4063]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When settings a navigation item to disabled, the menu item appears disabled, but it is still possible to interact with and navigate to the defined `href` by clicking on the disabled menu item.

Have to remove the `href` in order to disable the navigation.

### Expected behavior 🤔

I would expect that setting a menu item to disabled, would set the style _and_ disable navigation.

### Steps to reproduce 🕹

Sandbox link: https://stackblitz.com/edit/github-xkke3q?file=src%2FApp.tsx,src%2Fmain.tsx

I wasn't able to get the stackblitz example to start so no idea if it works. Failing that, this should be enough to demonstrate the behaviour:

```
        <HvTypography variant="title1">
          Disabled Menu Item does not dislable navigation
        </HvTypography>
        <HvVerticalNavigation open>
          <HvVerticalNavigationTree
            aria-label="Example 1 navigation"
            data={[
              {
                id: "00",
                label: "Google",
                href: "https://www.google.com",
              },
              {
                id: "01",
                label: "Bing",
                href: "https://www.bing.com",
                disabled: true,
              },
            ]}
            onChange={function _a() {}}
            selected="00"
          />
        </HvVerticalNavigation>
```

Steps to reproduce:

1. Click on the disabled "Bing" link
2. Browser will navigate to bing.com

### Context 🔦

Need to be able to disable unsupported menu items.

### Your Environment 🌎

Build tool: Vite 5
Device & OS: Windows 10, laptop)
Browser: Edge 122.0.2365.66
Other details n/a

**Comment by zettca** [comment]
Thanks for reporting this @MarkJBenson. We'll take a look 👍

**Comment by MEsteves22** [comment]
Hello 👋

This was addressed in the latest release: [@hitachivantara/uikit-react-core@5.64.2](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.64.2). Thanks 🙏
