### ISSUE TITLE
Issue after uprading to latest hv-uikit library

### ISSUE THREAD

**Issue by aanjum154** [lumada-design/hv-uikit-react#4069]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

After upgrading to latest hv-uikit library, facing below issues in our project:

![image](https://github.com/lumada-design/hv-uikit-react/assets/138006767/65a7ecdf-07dd-462c-810c-d7b1d501b166)

node version - v18.19.1
npm version - 10.2.4

### Steps to reproduce 🕹

Sandbox link: 

Steps to reproduce:

1.
2.
3.
4.

### Your Environment 🌎

Build tool: (e.g. Vite 4, Webpack 5)
Device & OS: (e.g. Windows 11 laptop, iPhone 13 iOS15)
Browser: (e.g. Chrome 112, Safari 15.4)
Other details (e.g. 4K resolution, ...)

**Comment by aanjum154** [comment]
[package.json](https://github.com/lumada-design/hv-uikit-react/files/14587587/package.json)

**Comment by aanjum154** [comment]
> [@babel/plugin-proposal-optional-chaining](https://babeljs.io/docs/babel-plugin-transform-optional-chaining#installation)

@MEsteves22 Yes adding this plugin solved the issue, thank you so much. But I am facing other errors after importing HvBarChart and other components from @hitachivantara/uikit-react-viz:

![image](https://github.com/lumada-design/hv-uikit-react/assets/138006767/3c1a6ea2-aed8-4544-8e48-5b498fafa53a)

Can you please tell me what is it that I am missing here!!!

**Comment by MEsteves22** [comment]
I'm glad it worked @aanjum154 🙏 

Do you have the following dependencies in your `node_modules`: `arquero`, `echarts`, and `echarts-for-react`? If not, can you try reinstalling your project again. They should come with `uikitt-react-viz` out of the box.

**Comment by aanjum154** [comment]
> echarts

Hey @MEsteves22, it worked after adding the dependencies arquero, echarts, and echarts-for-react in the package.json file. Thank you so much for your help!!!!
