### ISSUE TITLE
Table: "actions" column is limited by width

### ISSUE THREAD

**Issue by VitaliiSemchyshyn** [lumada-design/hv-uikit-react#4075]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

"actions" seems to expect content no wider than dropdown-menu button. When I try to use wider content - vertical scroll happens
If manually set width/max-width to the column - it works. Could be a workaround, but I'm interested if you have more flexible solution.
![image](https://github.com/lumada-design/hv-uikit-react/assets/154451209/8011d013-8225-4a6a-88cd-f505b73ea931)

### Expected behavior 🤔

I want to have some buttons as actions, as pictured on screen
![image](https://github.com/lumada-design/hv-uikit-react/assets/154451209/87da6251-2960-4189-a61c-e9001aac18af)

### Steps to reproduce 🕹

Sandbox link: 

Steps to reproduce:

1. Create HvTable with the last column with "actions" type.
2. In table body add two icon-buttons in the "actions" column.

### Your Environment 🌎

Build tool: (e.g. Vite 4, Webpack 5)
Device & OS: (e.g. Windows 11 laptop, iPhone 13 iOS15)
Browser: (e.g. Chrome 112, Safari 15.4)
Other details (e.g. 4K resolution, ...)

**Comment by zettca** [comment]
Hey @VitaliiSemchyshyn 👋

The purpose of the `"actions"` variant is to add the space for the just one action, and the vertical separator.
Looking at you mock (it doesn't have the separator), I believe you should be using the `"none"` variant (it just removes the padding)

Something like this:
```tsx
<HvTableCell variant="none">
  <div className="flex">
    <Abacus />
    <HvDropDownMenu placement="left" dataList={[]} />
  </div>
</HvTableCell>
```

Let us know if that helps 👍

**Comment by VitaliiSemchyshyn** [comment]
@zettca thanks for answer, I will let you know

**Comment by VitaliiSemchyshyn** [comment]
@zettca with variant="none" the column is not aligned to the right side of table

**Comment by VitaliiSemchyshyn** [comment]
@zettca Your example has "actions" in header, but "none" in body. With that combination it works, thanks!
Problem solved
