### ISSUE TITLE
Input: add ability to make input "unchecked".

### ISSUE THREAD

**Issue by VitaliiSemchyshyn** [lumada-design/hv-uikit-react#4083]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

I have a form with validations. The form can be cleared. In that case, I want to make inputs "unchecked", so that validation won't run until user interacts with input again.

**Comment by zettca** [comment]
Hey @VitaliiSemchyshyn 👋 

You can use the `status` prop to control the validation state of the input. You probably want `status="valid"` or `status="empty"`

Please let us know if that fixes the issue

**Comment by VitaliiSemchyshyn** [comment]
@zettca but I want status to be controlled by the Input itself. If i set it manually, then I will have to validate the value by myselfm right?

**Comment by zettca** [comment]
What you're describing is a custom controlled (by the user) behaviour; you'll have to control it yourself, yes.
`HvInput` isn't able to distinguish a "user input clear" (that should show validation errors eg. required) from your custom "reset form"

**Comment by VitaliiSemchyshyn** [comment]
@zettca got you. Thanks
