### ISSUE TITLE
HvQueryBuilder - Error in Value & (defaultValue) while changing the attributes list at run time.

### ISSUE THREAD

**Issue by vkumarakella** [lumada-design/hv-uikit-react#4109]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

We observed that when we are dynamically changing attributes based on object type, query builder is giving error (in Value component).

And so, can you please change the code from **attributes[attribute].type**  to **attributes[attribute]?.type** and let us know.
![query-error](https://github.com/lumada-design/hv-uikit-react/assets/129264654/b005bbd1-d090-461b-9856-371f2c457475)

https://github.com/lumada-design/hv-uikit-react/assets/129264654/6f9c9c6c-a1d7-4200-b8bf-25ba9f25a7df

### Expected behavior 🤔

The Component should not throw error and the Attribute list should get updated dynamically based on object type.

### Steps to reproduce 🕹

Sandbox link: 

Steps to reproduce:

1.
2.
3.
4.

### Context 🔦

Affecting the deliverables and release.

### Your Environment 🌎

Build tool: (e.g. Vite 4, Webpack 5)
Device & OS: (e.g. Windows 11 laptop, iPhone 13 iOS15)
Browser: (e.g. Chrome 112, Safari 15.4)
Other details (e.g. 4K resolution, ...)

**Comment by MEsteves22** [comment]
Hello 👋

Thanks for opening this issue. We'll take a look 🙏

**Comment by MEsteves22** [comment]
Fixed in [@hitachivantara/uikit-react-core@5.62.1](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.62.1)
