### ISSUE TITLE
onClose is triggered twice in HvDrawer 

### ISSUE THREAD

**Issue by ShubhamHitachi** [lumada-design/hv-uikit-react#4126]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

In HvDrawer component when we close the drawer by clicking outside(backdropClick), the `onClose` function is triggered twice. 

The twice triggering is random, it doesn't always trigger twice. I have added a sandbox link for reproducing the same. 

### Expected behavior 🤔

The onClose function should be triggered only once like it does in all other cases such as  `escapeKeyDown`, `cancelled`  and `undefined`. 

### Steps to reproduce 🕹

Sandbox link: 
https://codesandbox.io/p/sandbox/hvdrawer-wsjn3x

Steps to reproduce:

1. 
2. 
3.
4.

### Context 🔦

I have an action to be triggered when the drawer closes. Due to the issue, the action is triggered twice. 

### Your Environment 🌎

Build tool: Vite v5.2.7
Device & OS: Windows 10 laptop
Browser: Any

**Comment by MEsteves22** [comment]
Hello 👋
This was fixed in the latest version: [@hitachivantara/uikit-react-core@5.63.1](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.63.1). Thanks 🙏
