### ISSUE TITLE
How to change placeholder color locally?

### ISSUE THREAD

**Issue by VitaliiSemchyshyn** [lumada-design/hv-uikit-react#4146]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

I theme object there is "placeholderText" property, I assume it can change placeholder styles globally.
Is there a possibility to change placeholder color for disabled input, for example? Couldn't find how it get applied

**Comment by zettca** [comment]
Hey @VitaliiSemchyshyn 👋 

Are you using DS3 or DS5 theme? Keep in mind that `placeholderText` doesn't exist in DS5 and you should be using something else.

If you're trying to override the placeholder of:
- A single `HvInput`, you can override the `::placeholder` color of `HvInput`'s `input` class ([example](https://stackblitz.com/edit/github-jkksf2?file=src%2FApp.tsx%3AL10))
- All `HvInput` in the app, you can override the global `HvInput` classes ([example](https://stackblitz.com/edit/github-jkksf2?file=src%2FApp.tsx%3AL10,src%2Fmain.tsx%3AL17))


Let me know if that helps!

**Comment by VitaliiSemchyshyn** [comment]
@zettca Thank you, it helped!
Can close the ticket
