### ISSUE TITLE
How to increase size of radio?

### ISSUE THREAD

**Issue by VitaliiSemchyshyn** [lumada-design/hv-uikit-react#4150]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

Current version of radio has 16x16 size.
I want to increase it to 24x24 for my case. I need radion with semantic = true.
What is the right way? Setting width and heigh to svg increases circle, but when selected - it doesn't fill properly (see screenshot).
![image](https://github.com/lumada-design/hv-uikit-react/assets/154451209/bf7c0887-6a6f-4f95-b281-8633500e3f70)

**Comment by MEsteves22** [comment]
Hello 👋

You could add the following CSS to the radio:

```
classes={{
    root: css({
        "& svg": {
            width: 24,
            height: 24,
         },
        "& path": { transform: "scale(1.55)" },
    }),
}}
```

**Comment by VitaliiSemchyshyn** [comment]
@MEsteves22 thanks! I tried 'scale' just to svg, it also worked.
`
classes={{
    root: css({
        "& svg": {
            transform: scale(1.5),
         },
    }),
}}
`

**Comment by MEsteves22** [comment]
Yes, you can also use it directly in the svg. I didn't do it because the border width increases when using it there, but if it's okay for your use case great 🙏 there are less overrides
