### ISSUE TITLE
Sticky columns break UI when there are header groups in the table

### ISSUE THREAD

**Issue by leo-petliakov** [lumada-design/hv-uikit-react#4171]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

When applying sticky columns to a table with header groups, the UI for header breaks

### Expected behavior 🤔

Sticky columns should work with header groups

### Steps to reproduce 🕹

Sandbox link: https://stackblitz.com/edit/github-bjf7qa

Steps to reproduce:

1. Create a simple table using hv table hooks
2. Add some columns along with a grouped column with multiple columns inside 
3. Apply sticky to any column

### Your Environment 🌎

Build tool: Vite 4
Device & OS: Macbook 16 inch MacOS Ventura 13.6.6
Browser: Chrome 124.0.6367.119

**Comment by MEsteves22** [comment]
Hello @leo-petliakov 👋

Thanks for raising this issue, we'll take a look 🙏
