### ISSUE TITLE
HvDatePicker component not working with local environment. 

### ISSUE THREAD

**Issue by sarika-jamdade** [lumada-design/hv-uikit-react#4191]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

HvDatePicker is not working with local dev setup. When we create build version then only it works. 

For local setup getting following error - 
![image](https://github.com/lumada-design/hv-uikit-react/assets/126783161/d568c349-6572-4960-9043-c65c42e68345)

### Expected behavior 🤔

HvDatePicker should work with local dev setup as well

### Steps to reproduce 🕹

Sandbox link: 

Steps to reproduce:

1.
2.
3.
4.

### Your Environment 🌎

Build tool: (e.g. Vite 4, Webpack 5)
Device & OS: (e.g. Windows 11 laptop, iPhone 13 iOS15)
Browser: (e.g. Chrome 112, Safari 15.4)
Other details (e.g. 4K resolution, ...)

**Comment by zettca** [comment]
Please our [Stackblitz template](https://stackblitz.com/github/lumada-design/hv-uikit-react/tree/master/examples/uikit-vite-ts) to reproduce the issue, or tell us more about your environment

**Comment by MEsteves22** [comment]
Hello 👋 Due to inactivity I'll close the issue. Let us know if you still need help 🙏
