### ISSUE TITLE
Input Adornment Password field eye icon

### ISSUE THREAD

**Issue by vishnushekhar-globallogic** [lumada-design/hv-uikit-react#4193]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

spec: https://lumada-design.github.io/uikit/master/?path=/story/guides-forms-form-element-blocks-adornment--input-adornment

Eye icon behavior : if eye is open you can not see the password but if eye icon is closed you can see the password logically  its incorrect  

### Expected behavior 🤔

Ideally if we open eye then only we can see things same reverse behavior is expected 
Eye Open => Can see the password 
Eye Closed  => Can not see the password 

### Steps to reproduce 🕹

Sandbox link: 
https://lumada-design.github.io/uikit/master/?path=/story/guides-forms-form-element-blocks-adornment--input-adornment
Steps to reproduce:

1.Add password 
2.click  on eye icon
3.
4.

### Context 🔦

its not user friendly and funny 

### Your Environment 🌎

Build tool: (e.g. Vite 4, Webpack 5)
Device & OS: (e.g. Windows 11 laptop, iPhone 13 iOS15)
Browser: (e.g. Chrome 112, Safari 15.4)
Other details (e.g. 4K resolution, ...)

**Comment by zettca** [comment]
Hey @vishnushekhar-globallogic, thanks for your feedback.

The current implementation follows the [Design System spec](https://designsystem.hitachivantara.com/6c705d900/v/39412/p/6700f7-input/b/50959e). [Other](https://mui.com/base-ui/react-input/#adornments) [libraries](https://mantine.dev/core/password-input/) also implement it like this.

If you don't think that makes sense, please share your feedback with the Design System team 👍 

Closing as wont-fix

**Comment by vishnushekhar-globallogic** [comment]
Please check the implementation with other website like facebook current logic for eye is incorrect 
![image](https://github.com/lumada-design/hv-uikit-react/assets/167960307/64506774-9fe1-451d-a4db-1a28149b1c90)
