### ISSUE TITLE
 Pagination component (useHvPagination) page accept the float value if we change the pages

### ISSUE THREAD

**Issue by nikhilguptagl** [lumada-design/hv-uikit-react#4194]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

I am using useHvPagination component for Pagination showing data.
We have noticed that - in the input box of pagination component, user can enter float values. Screenshot below - 

![image](https://github.com/lumada-design/hv-uikit-react/assets/154490511/83655118-4238-498f-8bf3-fa80854d9e08)

### Expected behavior 🤔

Ideally, when using Pagination, we should be able to enter only natural values in the input box (1, 2, 3, 4, ----- and so on)

### Steps to reproduce 🕹

Sandbox link: 

Steps to reproduce:

1.
2.
3.
4.

### Context 🔦

We are trying to show the user data on the tables using useHvPagination but without the floating numbers.

### Your Environment 🌎

Build tool: (e.g. Vite 4)
Device & OS: (e.g. Windows 11 laptop)
Browser: (e.g. Chrome 112)

**Comment by zettca** [comment]
Hey @nikhilguptagl, thanks for reporting this 👋

**Comment by MEsteves22** [comment]
Hello 👋 This was fixed in [@hitachivantara/uikit-react-core@5.66.0](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.66.0). Thanks

**Comment by MEsteves22** [comment]
Hello 👋 This was fixed in [@hitachivantara/uikit-react-core@5.66.1](https://github.com/lumada-design/hv-uikit-react/releases/tag/%40hitachivantara%2Fuikit-react-core%405.66.1). Thanks

**Comment by nikhilguptagl** [comment]
Hi @MEsteves22, Thanks for fixing it, however we can still enter float values in the input box in the upgraded version '5.66.13'.
Screenshot - 
![bug](https://github.com/user-attachments/assets/bc5df451-f98f-4673-a2ee-4b405e5d4cc6)

Looping our QA as well who has raised this bug. cc @mayur050493

**Comment by MEsteves22** [comment]
Hello @nikhilguptagl 👋

Yes, technically you can still enter a decimal value. However, the value is rounded up once the input is blurred. Users will always be able to enter "2.5" since we can't prohibit the user from doing so. However, the value is then rounded up since decimals are not permitted. Let me know if I'm missing something there 🙏

**Comment by mayur050493** [comment]
Hi @MEsteves22 
However, the user interface only allows for the entry of integer values for pagination, prohibiting the entry of float values.

**Comment by MEsteves22** [comment]
Hello, the team talked and, unfortunately, we won't be changing the component to prohibit the user to type `.` or `,` as this is not part of our specs. Thanks 🙏
