### ISSUE TITLE
Time picker- Add support to hide seconds

### ISSUE THREAD

**Issue by sachinlandage88** [lumada-design/hv-uikit-react#4301]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

Hello Team,

The current Time picker doesn't support hiding seconds. Currently, this feature is available only for native time pickers but it doesn't fit into my requirement. so could you please add this feature?

Thank you,
Sachin

**Comment by zettca** [comment]
Hello @sachinlandage88, thanks for reporting this

**Comment by plagoa** [comment]
@sachinlandage88 this has been released in `v5.71.0`. Please let us know if you have any problem. I'll close this issue.
