### ISSUE TITLE
HvTimeAgo doesn't support date format?

### ISSUE THREAD

**Issue by shadahm-he** [lumada-design/hv-uikit-react#4324]
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Summary 💡

We are using your library for our project in Hitachi Energy.

There is one state where it goes something like:
`Yesterday at 1:44 PM`

We can't find a way to make this in 24h time (i.e: showing 13:44 instead), and that's the more popular time format where we are.

Am I missing something or this is a feature request?

**Comment by zettca** [comment]
Hey @shadahm-he

We do have issues with i18n which we're now addressing 👍 

Regarding the 24-hour question, just to clarify, do you need a custom date locale independent of the defined locale? For instance, in english the `en-US` uses 12-hour format, but `en-UK` uses the 24-hour format. eg:
```
en-UK > 16:12:10
en-US > 4:12:10 PM
```

Are you looking to customise it beyond the default locale rules? eg. `16:12:10` when users have `en-US` configured

**Comment by plagoa** [comment]
@shadahm-he `v5.73.0` includes a fix for this issue. Please take a look and let us know if that's enough for your use case.

**Comment by shadahm-he** [comment]
Hi guys. We are still using version v4.0.2 so we won't be testing this fix, since we have done a workaround in our repo.

But thank you that you've looked into it so fast :)
