### ISSUE TITLE
Color Picker - unable to fill "0" in R/G/B fields

### ISSUE THREAD

**Issue by VitaliiSemchyshyn** [lumada-design/hv-uikit-react#4459]
### Which UI Kit version is this bug for?

v5.x

### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Upon trying to fill 0 in R/G/B fields, value is not saved

### Expected behavior 🤔

0 to be valid value

### Steps to reproduce 🕹

Sandbox link: https://lumada-design.github.io/uikit/master/?path=/docs/widgets-color-picker--docs

Steps to reproduce:

1. Open color picker.
2. Choose color with R/G/B not 0.
3. Try to separately change R/G/B to 0.

### Context 🔦

If you fill 000000 in hex - R/G/B is set 0 automatically. But you can't change it to 0 manually.

### Your Environment 🌎

Build tool: (e.g. Vite 4, Webpack 5)
Device & OS: (e.g. Windows 11 laptop, iPhone 13 iOS15)
Browser: (e.g. Chrome 112, Safari 15.4)
Other details (e.g. 4K resolution, ...)

**Comment by plagoa** [comment]
Thanks for the feedback @VitaliiSemchyshyn . We've opened a bug to fix this.
